export interface AnimeDetail {
  id: number
  title: string
  year: number
  type: string
  image: string
  genre: string[]
  imdb: number
  description: string
  episodes?: number
  status: string
  youtubeTrailerId: string
  telegramLink: string
  language: string
  views?: number
}

export const animeDatabase: AnimeDetail[] = [
  {
    id: 1,
    title: "Spirited Away",
    year: 2001,
    type: "Movie",
    image: "/1id.jpg",
    genre: ["Action", "Drama", "Thriller"],
    imdb: 9.1,
    description: "A magical journey to a spirit world beyond imagination.",
    status: "Completed",
    youtubeTrailerId: "aL-97TEa43Y",
    telegramLink: "https://t.me/animeversebd/9",
    language: "Hindi",
    views: 1250,
  },
  {
    id: 2,
    title: "The Monkey King",
    year: 2023,
    type: "Movie",
    image: "/2id.jpg",
    genre: ["Action", "Supernatural", "Historical"],
    imdb: 5.6,
    description: "এক কিংবদন্তীর শুরু, এক অসাধারণ অভিযান।",
    status: "Completed",
    youtubeTrailerId: "0pmIANSKkdo",
    telegramLink: "https://t.me/animeverse_bd",
    language: "Hindi",
    views: 2340,
  },
  {
    id: 3,
    title: "Your Name",
    year: 2016,
    type: "Movie",
    image: "/3id.jpg",
    genre: ["Action", "School", "Supernatural"],
    imdb: 8.4,
    description: "দুই হৃদয়ের অলৌকিক গল্প, যা সময় ও দূরত্বকে ছাপিয়ে যায়।",
    status: "Completed",
    youtubeTrailerId: "_oWzYOwXn-o",
    telegramLink: "https://t.me/animeversebd/13",
    language: "Hindi",
    views: 3450,
  },
  {
    id: 4,
    title: "A Whisker Away",
    year: 2020,
    type: "Movie",
    image: "/4id.jpg",
    genre: ["Adventure", "Comedy", "Action"],
    imdb: 6.7,
    description: "A magical adventure with unexpected twists.",
    status: "Completed",
    youtubeTrailerId: "zGGp2RVoPdU",
    telegramLink: "https://t.me/animeversebd/17",
    language: "Hindi",
    views: 1890,
  },
  {
    id: 5,
    title: "Drifting Home",
    year: 2022,
    type: "Movie",
    image: "/5id.jpg",
    genre: ["Action", "Martial Arts", "Adventure"],
    imdb: 6.5,
    description: "A heartwarming story of friendship and adventure.",
    status: "Completed",
    youtubeTrailerId: "zY5O9JRPKLY",
    telegramLink: "https://t.me/animeversebd/19",
    language: "Hindi",
    views: 1567,
  },
  {
    id: 6,
    title: "Once Upon a Witch's Death Season 1",
    year: 2025,
    type: "TV Show",
    image: "/6id.jpg",
    genre: ["Action", "Adventure", "Martial Arts"],
    imdb: 8.7,
    description: "A thrilling tale of magic and mystery.",
    status: "Ongoing",
    youtubeTrailerId: "FerOCv5eOHI",
    telegramLink: "https://t.me/animeversebd/21",
    language: "Hindi",
    views: 2100,
  },
  {
    id: 7,
    title: "A Great Cleric Season 1",
    year: 2023,
    type: "TV Show",
    image: "/7id.jpg",
    genre: ["Superhero", "School", "Action"],
    imdb: 7.5,
    description: "An epic journey of a powerful cleric.",
    status: "Completed",
    youtubeTrailerId: "susqUMviH_E",
    telegramLink: "https://t.me/animeversebd/46",
    language: "Hindi",
    views: 1750,
  },
  {
    id: 8,
    title: "Rurouni Kenshin Season 1",
    year: 2023,
    type: "TV Show",
    image: "/8id.jpg",
    genre: ["Thriller", "Supernatural", "Psychological"],
    imdb: 7.9,
    description: "A legendary swordsman's journey through time.",
    status: "Completed",
    youtubeTrailerId: "ZONOltoCdP4",
    telegramLink: "https://t.me/animeversebd/73",
    language: "Hindi",
    views: 1900,
  },
  {
    id: 9,
    title: "A Couple of Cuckoos Season 1",
    year: 2022,
    type: "TV Show",
    image: "/9id.jpg",
    genre: ["Comedy", "Action", "Supernatural"],
    imdb: 7.1,
    description: "A hilarious romantic comedy with supernatural elements.",
    status: "Completed",
    youtubeTrailerId: "WtBwfWvUEqY",
    telegramLink: "https://t.me/animeversebd/82",
    language: "Hindi",
    views: 1600,
  },
  {
    id: 10,
    title: "The Misfit of Demon King Academy Season 1",
    year: 2020,
    type: "TV Show",
    image: "/10id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 7.3,
    description: "A powerful demon king returns to his academy.",
    status: "Completed",
    youtubeTrailerId: "e8YBesRKq_U",
    telegramLink: "https://t.me/animeversebd/137",
    language: "Hindi",
    views: 1800,
  },
  {
    id: 11,
    title: "Shangri La Frontier Season 2",
    year: 2025,
    type: "TV Show",
    image: "/11id.jpg",
    genre: ["Action", "Adventure", "Fantasy", "Game"],
    imdb: 8.6,
    description: "An epic gaming adventure continues.",
    status: "Ongoing",
    youtubeTrailerId: "R_7Okd4X1lU",
    telegramLink: "https://t.me/animeversebd/193",
    language: "Hindi",
    views: 2200,
  },
  {
    id: 12,
    title: "Attack on Titan Season 1",
    year: 2013,
    type: "TV Show",
    image: "/12id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 9.0,
    description: "Humanity fights for survival against giant titans.",
    status: "Completed",
    youtubeTrailerId: "LajOXSdyBeE",
    telegramLink: "https://t.me/animeversebd/198",
    language: "Hindi",
    views: 2500,
  },
  {
    id: 13,
    title: "Attack on Titan Season 2",
    year: 2017,
    type: "TV Show",
    image: "/13id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 8.9,
    description: "The battle against titans intensifies.",
    status: "Completed",
    youtubeTrailerId: "X2WGyFRKb8Y",
    telegramLink: "https://t.me/animeversebd/250",
    language: "Hindi",
    views: 2400,
  },
  {
    id: 14,
    title: "Attack on Titan Season 3",
    year: 2018,
    type: "TV Show",
    image: "/14id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 9.2,
    description: "Secrets of the titans are revealed.",
    status: "Completed",
    youtubeTrailerId: "mBGyz4G60cQ",
    telegramLink: "https://t.me/animeversebd/273",
    language: "Hindi",
    views: 2600,
  },
  {
    id: 15,
    title: "Attack on Titan Season 4",
    year: 2020,
    type: "TV Show",
    image: "/15id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 9.3,
    description: "The final season brings epic conclusions.",
    status: "Completed",
    youtubeTrailerId: "cR0zTG2czV0",
    telegramLink: "https://t.me/animeversebd/318",
    language: "Hindi",
    views: 2700,
  },
  {
    id: 16,
    title: "Olaf Presents Season 1",
    year: 2021,
    type: "TV Show",
    image: "/16id.jpg",
    genre: ["Animation", "Comedy", "Short"],
    imdb: 7.3,
    description: "Olaf presents hilarious Disney stories.",
    status: "Completed",
    youtubeTrailerId: "2Stzk2aopxs",
    telegramLink: "https://t.me/animeversebd/376",
    language: "English",
    views: 1700,
  },
  {
    id: 17,
    title: "Brave",
    year: 2012,
    type: "Movie",
    image: "/17id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 7.1,
    description: "A brave princess fights for her destiny.",
    status: "Completed",
    youtubeTrailerId: "fyP0IGEzr4s",
    telegramLink: "https://t.me/animeversebd/389",
    language: "English",
    views: 1650,
  },
  {
    id: 18,
    title: "DC League of Super-Pets",
    year: 2022,
    type: "Movie",
    image: "/18id.jpg",
    genre: ["Animation", "Action", "Comedy"],
    imdb: 7.2,
    description: "Superhero pets save the day.",
    status: "Completed",
    youtubeTrailerId: "dgtFO6ANznY",
    telegramLink: "https://t.me/animeversebd/391",
    language: "English/Hindi",
    views: 1750,
  },
  {
    id: 19,
    title: "Doraemon: Nobita's Chronicle of the Moon Exploration",
    year: 2019,
    type: "Movie",
    image: "/19id.jpg",
    genre: ["Animation", "Sci-Fi", "Adventure"],
    imdb: 6.7,
    description: "Doraemon and Nobita explore the moon.",
    status: "Completed",
    youtubeTrailerId: "w7Iz-zsltjw",
    telegramLink: "https://t.me/animeversebd/393",
    language: "Hindi",
    views: 1550,
  },
  {
    id: 20,
    title: "Justice Society: World War II",
    year: 2021,
    type: "Movie",
    image: "/20id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 6.4,
    description: "Superheroes fight in World War II.",
    status: "Completed",
    youtubeTrailerId: "qx2zoSk42BI",
    telegramLink: "https://t.me/animeversebd/395",
    language: "Hindi",
    views: 1450,
  },
  {
    id: 21,
    title: "Puss in Boots: The Last Wish",
    year: 2022,
    type: "Movie",
    image: "/21id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 7.8,
    description: "Puss in Boots goes on one last adventure.",
    status: "Completed",
    youtubeTrailerId: "tsTLlZ32SpI",
    telegramLink: "https://t.me/animeversebd/397",
    language: "Hindi",
    views: 1850,
  },
  {
    id: 22,
    title: "Constantine: City of Demons",
    year: 2018,
    type: "Movie",
    image: "/22id.jpg",
    genre: ["Animation", "Action", "Fantasy"],
    imdb: 7.4,
    description: "Constantine battles demons in the city.",
    status: "Completed",
    youtubeTrailerId: "6vL--ZrHC6U",
    telegramLink: "https://t.me/animeversebd/399",
    language: "English/Hindi",
    views: 1750,
  },
  {
    id: 23,
    title: "Doraemon: Nobita and the Kingdom of Clouds",
    year: 1992,
    type: "Movie",
    image: "/23id.jpg",
    genre: ["Animation", "Adventure", "Family"],
    imdb: 7.0,
    description: "Doraemon and friends discover a cloud kingdom.",
    status: "Completed",
    youtubeTrailerId: "6ndjhJo2zFw",
    telegramLink: "https://t.me/animeversebd/401",
    language: "Hindi",
    views: 1600,
  },
  {
    id: 24,
    title: "Hotel Transylvania 2",
    year: 2015,
    type: "Movie",
    image: "/24id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 6.6,
    description: "Dracula's family returns for more fun.",
    status: "Completed",
    youtubeTrailerId: "E3mL9H3C2OY",
    telegramLink: "https://t.me/animeversebd/403",
    language: "English/Hindi",
    views: 1500,
  },
  {
    id: 25,
    title: "Hotel Transylvania 3: Summer Vacation",
    year: 2018,
    type: "Movie",
    image: "/25id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 6.3,
    description: "Dracula goes on a summer vacation.",
    status: "Completed",
    youtubeTrailerId: "Qvt0KnhtPBk",
    telegramLink: "https://t.me/animeversebd/405",
    language: "Hindi",
    views: 1400,
  },
  {
    id: 26,
    title: "Ainbo: Spirit of the Amazon",
    year: 2021,
    type: "Movie",
    image: "/26id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 4.8,
    description: "A girl protects the Amazon rainforest.",
    status: "Completed",
    youtubeTrailerId: "PWRtf3pc14c",
    telegramLink: "https://t.me/animeversebd/407",
    language: "Hindi",
    views: 1200,
  },
  {
    id: 27,
    title: "Onward",
    year: 2020,
    type: "Movie",
    image: "/27id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 7.4,
    description: "Two brothers go on a magical quest.",
    status: "Completed",
    youtubeTrailerId: "dLXt8r1cQVk",
    telegramLink: "https://t.me/animeversebd/409",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 28,
    title: "Zootopia",
    year: 2016,
    type: "Movie",
    image: "/28id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 8.0,
    description: "A rabbit cop and fox con artist solve crimes.",
    status: "Completed",
    youtubeTrailerId: "X4XvU9FT0NM",
    telegramLink: "https://t.me/animeversebd/411",
    language: "Hindi",
    views: 1900,
  },
  {
    id: 29,
    title: "Ben 10: Destroy All Aliens",
    year: 2012,
    type: "Movie",
    image: "/29id.jpg",
    genre: ["Animation", "Action", "Sci-Fi"],
    imdb: 7.3,
    description: "Ben 10 fights to save the world.",
    status: "Completed",
    youtubeTrailerId: "zIYZQpknKZQ",
    telegramLink: "https://t.me/animeversebd/414",
    language: "Dual Audio",
    views: 1700,
  },
  {
    id: 30,
    title: "Shrek",
    year: 2001,
    type: "Movie",
    image: "/30id.jpg",
    genre: ["Animation", "Comedy", "Fantasy"],
    imdb: 7.1,
    description: "An ogre rescues a princess.",
    status: "Completed",
    youtubeTrailerId: "V2WydtFqZP8",
    telegramLink: "https://t.me/animeversebd/416",
    language: "English/Hindi",
    views: 1650,
  },
  {
    id: 31,
    title: "Shrek 2",
    year: 2004,
    type: "Movie",
    image: "/31id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 7.2,
    description: "Shrek meets his in-laws.",
    status: "Completed",
    youtubeTrailerId: "YxXp4EB6-fQ",
    telegramLink: "https://t.me/animeversebd/418",
    language: "English",
    views: 1700,
  },
  {
    id: 32,
    title: "The Jungle Book",
    year: 1967,
    type: "Movie",
    image: "/32id.jpg",
    genre: ["Animation", "Adventure", "Family"],
    imdb: 6.7,
    description: "A boy grows up in the jungle.",
    status: "Completed",
    youtubeTrailerId: "q6ZbvucX4Pg",
    telegramLink: "https://t.me/animeversebd/419",
    language: "Dual Audio",
    views: 1550,
  },
  {
    id: 33,
    title: "The Secret Life of Pets 2",
    year: 2019,
    type: "Movie",
    image: "/33id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 6.4,
    description: "Pets go on new adventures.",
    status: "Completed",
    youtubeTrailerId: "Id9iHnlOZaI",
    telegramLink: "https://t.me/animeversebd/421",
    language: "English",
    views: 1450,
  },
  {
    id: 34,
    title: "Turbo",
    year: 2013,
    type: "Movie",
    image: "/34id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 7.8,
    description: "A snail dreams of racing.",
    status: "Completed",
    youtubeTrailerId: "VlRtm8Gh9PQ",
    telegramLink: "https://t.me/animeversebd/423",
    language: "Dual Audio",
    views: 2890,
  },
  {
    id: 35,
    title: "White Snake",
    year: 2019,
    type: "Movie",
    image: "/35id.jpg",
    genre: ["Animation", "Fantasy", "Romance"],
    imdb: 7.4,
    description: "A magical love story unfolds.",
    status: "Completed",
    youtubeTrailerId: "RYKRko-yaO4",
    telegramLink: "https://t.me/animeversebd/425",
    language: "Dual Audio",
    views: 1750,
  },
  {
    id: 36,
    title: "Wonder Park",
    year: 2019,
    type: "Movie",
    image: "/36id.jpg",
    genre: ["Animation", "Family", "Fantasy"],
    imdb: 7.0,
    description: "A girl brings her imagination to life.",
    status: "Completed",
    youtubeTrailerId: "kNIyjsmoKts",
    telegramLink: "https://t.me/animeversebd/427",
    language: "English/Hindi",
    views: 1678,
  },
  {
    id: 37,
    title: "Mojib Bai",
    year: 2015,
    type: "Movie",
    image: "/37id.jpg",
    genre: ["Animation", "Adventure", "Action"],
    imdb: 6.6,
    description: "A Bangladeshi animated adventure.",
    status: "Completed",
    youtubeTrailerId: "givLtqsybMo",
    telegramLink: "https://t.me/animeversebd/429",
    language: "Bangla",
    views: 1500,
  },
  {
    id: 38,
    title: "Madan Senki Ryukendo",
    year: 2006,
    type: "TV Show",
    image: "/38id.jpg",
    genre: ["Action", "Fantasy", "Tokusatsu"],
    imdb: 7.3,
    description: "A warrior fights for justice.",
    status: "Completed",
    youtubeTrailerId: "vNgF_ZbVZHk",
    telegramLink: "https://t.me/animeversebd/431",
    language: "Japanese/English",
    views: 1700,
  },
  {
    id: 39,
    title: "What If... Season 1",
    year: 2021,
    type: "TV Show",
    image: "/39id.jpg",
    genre: ["Animation", "Action", "Sci-Fi"],
    imdb: 7.1,
    description: "Explore alternate Marvel universes.",
    status: "Completed",
    youtubeTrailerId: "I7ztyv9dwgo",
    telegramLink: "https://t.me/animeversebd/536",
    language: "English/Hindi",
    views: 1650,
  },
  {
    id: 40,
    title: "SK8 the Infinity Season 1",
    year: 2021,
    type: "TV Show",
    image: "/40id.jpg",
    genre: ["Sports", "Action", "Comedy"],
    imdb: 7.2,
    description: "Underground skateboarding battles.",
    status: "Completed",
    youtubeTrailerId: "cBPPj83KjTQ",
    telegramLink: "https://t.me/animeversebd/555",
    language: "Japanese/Hindi",
    views: 1700,
  },
  {
    id: 41,
    title: "Death Note Season 1",
    year: 2006,
    type: "TV Show",
    image: "/41id.jpg",
    genre: ["Mystery", "Supernatural", "Thriller"],
    imdb: 8.9,
    description: "A notebook that can kill anyone.",
    status: "Completed",
    youtubeTrailerId: "R5JgNbmQBcY",
    telegramLink: "https://t.me/animeversebd/578",
    language: "Japanese/Hindi",
    views: 2400,
  },
  {
    id: 42,
    title: "Roll No. 21 Season 1",
    year: 2010,
    type: "TV Show",
    image: "/42id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 8.1,
    description: "A student's hilarious adventures.",
    status: "Completed",
    youtubeTrailerId: "Zx4Yu2cujqI",
    telegramLink: "https://t.me/animeversebd/585",
    language: "Hindi",
    views: 2000,
  },
  {
    id: 43,
    title: "Roll No. 21 Season 2",
    year: 2013,
    type: "TV Show",
    image: "/43id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 7.8,
    description: "More adventures of Roll No. 21.",
    status: "Completed",
    youtubeTrailerId: "LTeXi8LgTy4",
    telegramLink: "https://t.me/animeversebd/632",
    language: "Dual Audio",
    views: 1900,
  },
  {
    id: 44,
    title: "Baki Hanma Season 2",
    year: 2023,
    type: "TV Show",
    image: "/44id.jpg",
    genre: ["Action", "Martial Arts", "Anime"],
    imdb: 7.4,
    description: "Intense martial arts battles.",
    status: "Completed",
    youtubeTrailerId: "KN98VzNwjOY",
    telegramLink: "https://t.me/animeversebd/685",
    language: "Japanese/Hindi",
    views: 1750,
  },
  {
    id: 45,
    title: "Blue Eye Samurai Season 1",
    year: 2023,
    type: "TV Show",
    image: "/45id.jpg",
    genre: ["Animation", "Action", "Drama"],
    imdb: 7.0,
    description: "A samurai's quest for revenge.",
    status: "Completed",
    youtubeTrailerId: "WfzXxTq_W6k",
    telegramLink: "https://t.me/animeversebd/738",
    language: "Hindi/Japanese",
    views: 4567,
  },
  {
    id: 46,
    title: "Puss in Boots",
    year: 2011,
    type: "Movie",
    image: "/46id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 6.6,
    description: "The origin story of Puss in Boots.",
    status: "Completed",
    youtubeTrailerId: "tsTLlZ32SpI",
    telegramLink: "https://t.me/animeversebd/755",
    language: "English/Hindi",
    views: 2234,
  },
  {
    id: 47,
    title: "Invincible Season 1",
    year: 2021,
    type: "TV Show",
    image: "/47id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 6.6,
    description: "A young superhero's journey begins.",
    status: "Completed",
    youtubeTrailerId: "qR2xlrQiHDk",
    telegramLink: "https://t.me/animeversebd/757",
    language: "English/Hindi",
    views: 1500,
  },
  {
    id: 48,
    title: "Invincible Season 2",
    year: 2023,
    type: "TV Show",
    image: "/48id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 6.6,
    description: "Invincible faces greater challenges.",
    status: "Completed",
    youtubeTrailerId: "13ahG2dEiWQ",
    telegramLink: "https://t.me/animeversebd/776",
    language: "English/Hindi",
    views: 1500,
  },
  {
    id: 49,
    title: "Onimusha Season 1",
    year: 2023,
    type: "TV Show",
    image: "/49id.jpg",
    genre: ["Animation", "Action", "Samurai"],
    imdb: 6.6,
    description: "A samurai fights supernatural forces.",
    status: "Completed",
    youtubeTrailerId: "SqWxZEvMrdo",
    telegramLink: "https://t.me/animeversebd/779",
    language: "Japanese/Hindi",
    views: 1500,
  },
  {
    id: 50,
    title: "Tokyo Revengers Season 2",
    year: 2023,
    type: "TV Show",
    image: "/50id.jpg",
    genre: ["Action", "Drama", "Supernatural"],
    imdb: 8.2,
    description: "Time travel and gang warfare.",
    status: "Completed",
    youtubeTrailerId: "eNZSurcYTW8",
    telegramLink: "https://t.me/animeversebd/797",
    language: "Japanese/Hindi",
    views: 2100,
  },
  {
    id: 51,
    title: "Captain Laserhawk: A Blood Dragon Remix Season 1",
    year: 2023,
    type: "TV Show",
    image: "/51id.jpg",
    genre: ["Animation", "Action", "Sci-Fi"],
    imdb: 7.9,
    description: "A cyberpunk action adventure.",
    status: "Completed",
    youtubeTrailerId: "1cqWBOVszYo",
    telegramLink: "https://t.me/animeversebd/825",
    language: "English",
    views: 1900,
  },
  {
    id: 52,
    title: "Ultraman Season 3",
    year: 2023,
    type: "TV Show",
    image: "/52id.jpg",
    genre: ["Action", "Sci-Fi", "Superhero"],
    imdb: 9.0,
    description: "The ultimate superhero battles.",
    status: "Completed",
    youtubeTrailerId: "Tvb-9DWt45Q",
    telegramLink: "https://t.me/animeversebd/837",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 53,
    title: "Rurouni Kenshin Season 1 Ep 5-8",
    year: 2023,
    type: "TV Show",
    image: "/53id.jpg",
    genre: ["Historical", "Action", "Romance"],
    imdb: 8.0,
    description: "A legendary swordsman's tale.",
    status: "Completed",
    youtubeTrailerId: "ZONOltoCdP4",
    telegramLink: "https://t.me/animeversebd/862",
    language: "Japanese/Hindi",
    views: 3789,
  },
  {
    id: 54,
    title: "Rurouni Kenshin Season 1 Ep 13-19",
    year: 2023,
    type: "TV Show",
    image: "/54id.jpg",
    genre: ["Historical", "Action", "Romance"],
    imdb: 9.0,
    description: "Kenshin's journey continues.",
    status: "Completed",
    youtubeTrailerId: "ZONOltoCdP4",
    telegramLink: "https://t.me/animeversebd/871",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 55,
    title: "Justice League Season 1",
    year: 2001,
    type: "TV Show",
    image: "/55id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 9.2,
    description: "Earth's mightiest heroes unite.",
    status: "Completed",
    youtubeTrailerId: "9Wly6N7dSkM",
    telegramLink: "https://t.me/animeversebd/886",
    language: "English/Hindi",
    views: 5678,
  },
  {
    id: 56,
    title: "Baki Hanma Season 1",
    year: 2023,
    type: "TV Show",
    image: "/56id.jpg",
    genre: ["Action", "Martial Arts", "Anime"],
    imdb: 8.5,
    description: "The strongest fighter emerges.",
    status: "Completed",
    youtubeTrailerId: "pRYZRvYGMtc",
    telegramLink: "https://t.me/animeversebd/939",
    language: "Japanese/Hindi",
    views: 2200,
  },
  {
    id: 57,
    title: "Pokémon Ultimate Journeys Season 1",
    year: 2022,
    type: "TV Show",
    image: "/57id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 7.3,
    description: "Ash's ultimate Pokémon journey.",
    status: "Completed",
    youtubeTrailerId: "wyrWFzV5U5Y",
    telegramLink: "https://t.me/animeversebd/964",
    language: "Japanese",
    views: 1700,
  },
  {
    id: 58,
    title: "Pokémon Ultimate Journeys Season 2",
    year: 2023,
    type: "TV Show",
    image: "/58id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 9.0,
    description: "The journey reaches new heights.",
    status: "Completed",
    youtubeTrailerId: "sR1hzqn8k5w",
    telegramLink: "https://t.me/animeversebd/991",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 59,
    title: "Scott Pilgrim Takes Off Season 1",
    year: 2023,
    type: "TV Show",
    image: "/59id.jpg",
    genre: ["Animation", "Comedy", "Romance", "Action"],
    imdb: 8.6,
    description: "A fresh take on Scott Pilgrim.",
    status: "Completed",
    youtubeTrailerId: "WAqJZdsV3mo",
    telegramLink: "https://t.me/animeversebd/1024",
    language: "English/Hindi",
    views: 2200,
  },
  {
    id: 60,
    title: "Ultraman Season 2",
    year: 2023,
    type: "TV Show",
    image: "/60id.jpg",
    genre: ["Action", "Sci-Fi", "Superhero"],
    imdb: 9.0,
    description: "Ultraman returns stronger.",
    status: "Completed",
    youtubeTrailerId: "AudT7Av-pv4",
    telegramLink: "https://t.me/animeversebd/1041",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 61,
    title: "Solo Leveling Season 1",
    year: 2024,
    type: "TV Show",
    image: "/61id.jpg",
    genre: ["Action", "Fantasy", "Adventure"],
    imdb: 8.4,
    description: "A hunter rises to power.",
    status: "Completed",
    youtubeTrailerId: "-tJMyIXjn9I",
    telegramLink: "https://t.me/animeversebd/1054",
    language: "Japanese/Hindi",
    views: 2100,
  },
  {
    id: 62,
    title: "Ultraman Season 1",
    year: 2019,
    type: "TV Show",
    image: "/62id.jpg",
    genre: ["Action", "Sci-Fi", "Superhero"],
    imdb: 6.8,
    description: "The beginning of Ultraman.",
    status: "Completed",
    youtubeTrailerId: "hLfNecWqzJs",
    telegramLink: "https://t.me/animeversebd/1057",
    language: "Japanese",
    views: 1800,
  },
  {
    id: 63,
    title: "Akuma Kun Season 1",
    year: 2023,
    type: "TV Show",
    image: "/63id.jpg",
    genre: ["Fantasy", "Supernatural", "Adventure"],
    imdb: 6.5,
    description: "A demon's supernatural adventures.",
    status: "Completed",
    youtubeTrailerId: "ZZQ7BaCunsw",
    telegramLink: "https://t.me/animeversebd/1084",
    language: "Japanese/Hindi",
    views: 1600,
  },
  {
    id: 64,
    title: "My Daemon Season 1",
    year: 2023,
    type: "TV Show",
    image: "/64id.jpg",
    genre: ["Fantasy", "Sci-Fi", "Drama"],
    imdb: 6.7,
    description: "A girl and her daemon companion.",
    status: "Completed",
    youtubeTrailerId: "vYTKsskxPV0",
    telegramLink: "https://t.me/animeversebd/1109",
    language: "Japanese/Hindi",
    views: 1700,
  },
  {
    id: 65,
    title: "Prison School Season 1",
    year: 2015,
    type: "TV Show",
    image: "/65id.jpg",
    genre: ["Comedy", "Ecchi", "School Life"],
    imdb: 7.6,
    description: "Boys in an all-girls prison.",
    status: "Completed",
    youtubeTrailerId: "l1v5WqCJva4",
    telegramLink: "https://t.me/animeversebd/1136",
    language: "Japanese/Hindi",
    views: 1800,
  },
  {
    id: 66,
    title: "Spy x Family Season 1",
    year: 2022,
    type: "TV Show",
    image: "/66id.jpg",
    genre: ["Action", "Comedy", "Family"],
    imdb: 8.3,
    description: "A spy, assassin, and psychic form a family.",
    status: "Completed",
    youtubeTrailerId: "fi_k0iAN8BE",
    telegramLink: "https://t.me/animeversebd/1161",
    language: "Japanese/Hindi",
    views: 2000,
  },
  {
    id: 67,
    title: "Mashle: Magic and Muscles Season 1",
    year: 2023,
    type: "TV Show",
    image: "/67id.jpg",
    genre: ["Fantasy", "Comedy", "Action"],
    imdb: 7.4,
    description: "Magic meets muscles in this adventure.",
    status: "Completed",
    youtubeTrailerId: "nDHAgFP3wxU",
    telegramLink: "https://t.me/animeversebd/1212",
    language: "Japanese/Hindi",
    views: 1900,
  },
  {
    id: 68,
    title: "My Love Story with Yamada-kun at Lv999",
    year: 2023,
    type: "TV Show",
    image: "/68id.jpg",
    genre: ["Romance", "Comedy", "Slice of Life"],
    imdb: 7.5,
    description: "A gamer love story unfolds.",
    status: "Completed",
    youtubeTrailerId: "im1jnkHA7wg",
    telegramLink: "https://t.me/animeversebd/1235",
    language: "Hindi/Japanese",
    views: 1750,
  },
  {
    id: 69,
    title: "Sgt. Stubby: An American Hero",
    year: 2018,
    type: "Movie",
    image: "/69id.jpg",
    genre: ["Adventure", "Family", "History"],
    imdb: 6.8,
    description: "A dog's heroic journey in war.",
    status: "Completed",
    youtubeTrailerId: "n3mbKogOWJ0",
    telegramLink: "https://t.me/animeversebd/1258",
    language: "English",
    views: 1600,
  },
  {
    id: 70,
    title: "Stuart Little",
    year: 1999,
    type: "Movie",
    image: "/70id.jpg",
    genre: ["Adventure", "Family", "Comedy"],
    imdb: 6.7,
    description: "A mouse's adventures in the city.",
    status: "Completed",
    youtubeTrailerId: "Wlo-sYrADlw",
    telegramLink: "https://t.me/animeversebd/1260",
    language: "Hindi",
    views: 1550,
  },
  {
    id: 71,
    title: "Stuart Little 2",
    year: 2002,
    type: "Movie",
    image: "/71id.jpg",
    genre: ["Adventure", "Family", "Comedy"],
    imdb: 6.7,
    description: "Stuart's new adventure continues.",
    status: "Completed",
    youtubeTrailerId: "k--OdtbKyqE",
    telegramLink: "https://t.me/animeversebd/1262",
    language: "Hindi",
    views: 1600,
  },
  {
    id: 72,
    title: "Stuart Little 3",
    year: 2005,
    type: "Movie",
    image: "/72id.jpg",
    genre: ["Adventure", "Family", "Comedy"],
    imdb: 6.7,
    description: "Stuart's final adventure.",
    status: "Completed",
    youtubeTrailerId: "trBgCyZpaa4",
    telegramLink: "https://t.me/animeversebd/1264",
    language: "Hindi",
    views: 1650,
  },
  {
    id: 73,
    title: "I Want to Eat Your Pancreas",
    year: 2018,
    type: "Movie",
    image: "/73id.jpg",
    genre: ["Drama", "Romance"],
    imdb: 8.1,
    description: "A touching love story.",
    status: "Completed",
    youtubeTrailerId: "uqQySB0NO4U",
    telegramLink: "https://t.me/animeversebd/1270",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 74,
    title: "Suzume",
    year: 2022,
    type: "Movie",
    image: "/74id.jpg",
    genre: ["Fantasy", "Adventure", "Drama"],
    imdb: 7.6,
    description: "A girl's magical journey.",
    status: "Completed",
    youtubeTrailerId: "ciQc8lfvSm0",
    telegramLink: "https://t.me/animeversebd/1272",
    language: "Hindi",
    views: 1800,
  },
  {
    id: 75,
    title: "Adam's Sweet Agony",
    year: 2023,
    type: "TV Show",
    image: "/75id.jpg",
    genre: ["Romance", "Sci-Fi", "Adult Comedy"],
    imdb: 7.6,
    description: "A romantic sci-fi comedy.",
    status: "Completed",
    youtubeTrailerId: "DzhRc0fsVrY",
    telegramLink: "https://t.me/animeversebd/1274",
    language: "Japanese",
    views: 1750,
  },
  {
    id: 76,
    title: "Bye Bye, Earth Season 1",
    year: 2024,
    type: "TV Show",
    image: "/76id.jpg",
    genre: ["Fantasy", "Adventure", "Drama"],
    imdb: 8.2,
    description: "An epic farewell to Earth.",
    status: "Ongoing",
    youtubeTrailerId: "33rmUkfc7tM",
    telegramLink: "https://t.me/animeversebd/1289",
    language: "Hindi",
    views: 1900,
  },
  {
    id: 77,
    title: "Dr. Stone Season 1",
    year: 2019,
    type: "TV Show",
    image: "/77id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 8.6,
    description: "Science rebuilds civilization.",
    status: "Completed",
    youtubeTrailerId: "Zlf8N7yrPwg",
    telegramLink: "https://t.me/animeversebd/1311",
    language: "English/Hindi",
    views: 2100,
  },
  {
    id: 78,
    title: "Dr. Stone: Stone Wars Season 2",
    year: 2021,
    type: "TV Show",
    image: "/78id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 9.1,
    description: "The stone wars intensify.",
    status: "Completed",
    youtubeTrailerId: "Nf8HZT3orUE",
    telegramLink: "https://t.me/animeversebd/1360",
    language: "English/Hindi",
    views: 2300,
  },
  {
    id: 79,
    title: "My Happy Marriage Season 1",
    year: 2023,
    type: "TV Show",
    image: "/79id.jpg",
    genre: ["Romance", "Drama", "Fantasy"],
    imdb: 7.6,
    description: "A marriage of convenience becomes love.",
    status: "Completed",
    youtubeTrailerId: "XoduKRPJeTI",
    telegramLink: "https://t.me/animeversebd/1383",
    language: "Japanese/Hindi",
    views: 1850,
  },
  {
    id: 80,
    title: "Lord of the Mysteries Season 1",
    year: 2025,
    type: "TV Show",
    image: "/80id.jpg",
    genre: ["Mystery", "Fantasy", "Action", "Suspense"],
    imdb: 8.6,
    description: "Mysteries unfold in a dark world.",
    status: "Ongoing",
    youtubeTrailerId: "Pdv0Uoh-brs",
    telegramLink: "https://t.me/animeversebd/1410",
    language: "Chinese/Hindi",
    views: 2200,
  },
  {
    id: 81,
    title: "Sakamoto Days Season 1",
    year: 2025,
    type: "TV Show",
    image: "/81id.jpg",
    genre: ["Action", "Comedy", "Thriller"],
    imdb: 8.2,
    description: "A retired assassin's peaceful days.",
    status: "Ongoing",
    youtubeTrailerId: "13pu4O72Rs4",
    telegramLink: "https://t.me/animeversebd/1429",
    language: "Japanese/Hindi",
    views: 2000,
  },
  {
    id: 82,
    title: "Watchmen",
    year: 2009,
    type: "Movie",
    image: "/82id.jpg",
    genre: ["Action", "Mystery", "Drama", "Superhero"],
    imdb: 7.6,
    description: "Superheroes in a dark world.",
    status: "Completed",
    youtubeTrailerId: "oUk6l8LCdCM",
    telegramLink: "https://t.me/animeversebd/1469",
    language: "English/Hindi",
    views: 1900,
  },
  {
    id: 83,
    title: "Watchmen",
    year: 2024,
    type: "Movie",
    image: "/83id.jpg",
    genre: ["Action", "Mystery", "Drama", "Superhero"],
    imdb: 9.0,
    description: "A new take on Watchmen.",
    status: "Completed",
    youtubeTrailerId: "Gzt7e1eP2hs",
    telegramLink: "https://t.me/animeversebd/1471",
    language: "English/Hindi",
    views: 2100,
  },
  {
    id: 84,
    title: "Demon Slayer: Kimetsu no Yaiba – Infinity Castle",
    year: 2025,
    type: "Movie",
    image: "/84id.jpg",
    genre: ["Anime", "Action", "Fantasy", "Adventure"],
    imdb: 8.0,
    description: "The final battle begins.",
    status: "Ongoing",
    youtubeTrailerId: "x7uLutVRBfI",
    telegramLink: "https://t.me/animeversebd/1486",
    language: "Japanese",
    views: 2000,
  },
  {
    id: 85,
    title: "Tower of God Season 1",
    year: 2020,
    type: "TV Show",
    image: "/85id.jpg",
    genre: ["Fantasy", "Adventure", "Mystery"],
    imdb: 7.6,
    description: "Climbing the mysterious tower.",
    status: "Completed",
    youtubeTrailerId: "9GJAE8Kj5Z4",
    telegramLink: "https://t.me/animeversebd/1488",
    language: "Japanese/Hindi",
    views: 1800,
  },
  {
    id: 86,
    title: "Demon Slayer: Kimetsu no Yaiba – Infinity Castle",
    year: 2025,
    type: "Movie",
    image: "/86id.jpg",
    genre: ["Action", "Fantasy", "Adventure"],
    imdb: 9.2,
    description: "The ultimate demon slayer battle.",
    status: "Ongoing",
    youtubeTrailerId: "0pdC1l6M8rU",
    telegramLink: "https://t.me/animeversebd/1503",
    language: "Hindi",
    views: 2300,
  },
  {
    id: 87,
    title: "The God of High School",
    year: 2020,
    type: "TV Show",
    image: "/87id.jpg",
    genre: ["Action", "Fantasy", "Martial Arts"],
    imdb: 7.2,
    description: "High school martial arts tournament.",
    status: "Completed",
    youtubeTrailerId: "yKsM3eceKWk",
    telegramLink: "https://t.me/animeversebd/1505",
    language: "Japanese/Hindi",
    views: 1750,
  },
  {
    id: 88,
    title: "Naruto Shippuden Season 1",
    year: 2002,
    type: "TV Show",
    image: "/88id.jpg",
    genre: ["Animation", "Action", "Adventure", "Fantasy"],
    imdb: 8.4,
    description: "Naruto's epic ninja journey.",
    status: "Completed",
    youtubeTrailerId: "voAYyJwgQ3I",
    telegramLink: "https://t.me/animeversebd/1508",
    language: "Hindi",
    views: 2200,
  },
  {
    id: 89,
    title: "Oggy and the Cockroaches Season 1",
    year: 1998,
    type: "TV Show",
    image: "/89id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 7.4,
    description: "A cat's hilarious battles with cockroaches.",
    status: "Completed",
    youtubeTrailerId: "m67kaN-6VQk",
    telegramLink: "https://t.me/animeversebd/1526",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 90,
    title: "Yoasobi Gurashi! (2024) Season 1",
    year: 2024,
    type: "TV Show",
    image: "/90id.jpg",
    genre: ["Animation", "Romance", "Slice of Life"],
    imdb: 7.4,
    description: "দুই শৈশবের বন্ধুর অপ্রত্যাশিত মিলন—একটি রুমে বসবাস, একটি গোপন রহস্য, আর রাতের গভীরে উঠে আসা অনুভূতির গল্প।",
    status: "Completed",
    youtubeTrailerId: "OWHj6smKlsk",
    telegramLink: "https://t.me/animeversebd/1538",
    language: "hindi dubbed",
    views: 1700,
  },
  {
    id: 91,
    title: "Naruto Shippuden  – Season 2 [Episode 1-32]",
    year: 2004,
    type: "TV Show",
    image: "/91id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 8.4,
    description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
    status: "Completed",
    youtubeTrailerId: "hyapq_q_kvY",
    telegramLink: "https://t.me/animeversebd/1568",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 92,
    title: "Yoasobi Gurashi! (2024) Season 1 part 2",
    year: 2024,
    type: "TV Show",
    image: "/92id.jpg",
    genre: ["Animation", "Romance", "Slice of Life"],
    imdb: 7.4,
    description: "দুই শৈশবের বন্ধুর অপ্রত্যাশিত মিলন—একটি রুমে বসবাস, একটি গোপন রহস্য, আর রাতের গভীরে উঠে আসা অনুভূতির গল্প।",
    status: "Completed",
    youtubeTrailerId: "OWHj6smKlsk",
    telegramLink: "https://t.me/animeversebd/1592",
    language: "hindi dubbed",
    views: 1700,
  },
  {
    id: 93,
    title: "Fire Force (Season 2 – 2020)",
    year: 2020,
    type: "TV Show",
    image: "/93id.jpg",
    genre: ["Animation", "Supernatural", "Shounen"],
    imdb: 7.6,
    description: "Special Fire Force Company 8 আবারও নামছে নতুন শত্রুর মুখোমুখি হতে—Infernals দমন, White-Clad এর ষড়যন্ত্র আর শিনরার অতীতের রহস্য উন্মোচনের লড়াই। ",
    status: "Completed",
    youtubeTrailerId: "Clr3JzxtAU4",
    telegramLink: "https://t.me/animeversebd/1597",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 94,
    title: "Motu Patlu (Season 1 – Bangla Dubbed)",
    year: 2015,
    type: "TV Show",
    image: "/94id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 6.5,
    description: "ফুরফুরিগঞ্জের দুষ্টু জুটি—মোটু আর পাতলু, মজার মজার কাণ্ডকারখানা আর হাস্যকর অ্যাডভেঞ্চারে ভরপুর।",
    status: "Completed",
    youtubeTrailerId: "nb7eXOnflw4",
    telegramLink: "https://t.me/animeversebd/1648",
    language: "Dubbed in Bangla",
    views: 1700,
  },
  {
    id: 95,
    title: "Naruto Shippuden  – Season 3 [Episode 1-18]",
    year: 2005,
    type: "TV Show",
    image: "/95id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 7.4,
    description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
    status: "Completed",
    youtubeTrailerId: "-1TKGtX8lJY",
    telegramLink: "https://t.me/animeversebd/1650",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 96,
    title: "Marvel Zombies: Season 1 (2025)",
    year: 2025,
    type: "TV Show",
    image: "/96id.jpg",
    genre: ["Animation", "Horror", "Superhero"],
    imdb: 8.4,
    description: "এক বিকল্প বাস্তবতায় পৃথিবীজুড়ে ছড়িয়ে পড়ে জম্বি ভাইরাস—যেখানে পরিচিত সুপারহিরোরা নিজেরাই হয়ে যায় ভয়ঙ্কর শিকারি।",
    status: "Completed",
    youtubeTrailerId: "UPAr5zef2Pk",
    telegramLink: "https://t.me/animeversebd/1693",
    language: "English",
    views: 1700,
  },
  {
    id: 97,
    title: "Doraemon: Nobita’s Art World Tales (2024)",
    year: 2024,
    type: "TV Show",
    image: "/97id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 9.7,
    description: "নোবিতা ও ডোরেমন এবার ঘুরে বেড়ায় চিত্রকলার জগতে! রঙ, কল্পনা আর রোমাঞ্চে ভরা এই সিনেমা ছোট-বড় সবার মন ছুঁয়ে যাবে।",
    status: "Completed",
    youtubeTrailerId: "3kW9tWoJfeM",
    telegramLink: "https://t.me/animeversebd/1784",
    language: "Japanese",
    views: 1700,
  },
  {
    id: 98,
    title: "Naruto Shippuden  – Season 4 [Episode 1-17]",
    year: 2007,
    type: "TV Show",
    image: "/98id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 7.4,
    description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
    status: "Completed",
    youtubeTrailerId: "zD8GPACmks8",
    telegramLink: "https://t.me/animeversebd/1786",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 99,
    title: "Tom and Jerry – Season 1 (1940-Present)",
    year: 1940,
    type: "TV Show",
    image: "/99id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 8.4,
    description: "চিরচেনা বিড়াল-ইঁদুরের দুষ্টুমি, মারামারি আর হাস্যরসের অনন্ত যুদ্ধ—Tom & Jerry মানেই শৈশবের স্মৃতি!",
    status: "Completed",
    youtubeTrailerId: "hgLV7qyWU04",
    telegramLink: "https://t.me/animeversebd/1824",
    language: "English",
    views: 1700,
  },
  {
    id: 100,
    title: "Motu Patlu vs the ghost house.",
    year: 1998,
    type: "TV Show",
    image: "/100id.jpg",
    genre: ["Animation", "Comedy", "Kids"],
    imdb: 6.9,
    description: "ফুরফুরে ফুরফুরি নগরের দুই বন্ধু মটু-পাটলুর দুষ্টুমি ও হাসির অভিযান—প্রতিটি পর্বেই নতুন কাণ্ড!",
    status: "Completed",
    youtubeTrailerId: "k0N7N09Viy8",
    telegramLink: "https://t.me/animeversebd/1826",
    language: "Bangla Dubbed",
    views: 1700,
  },
  {
    id: 101,
    title: "Naruto Shippuden  – Season 5 [Episode 1-24]",
    year: 2008,
    type: "TV Show",
    image: "/101id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 8.4,
    description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
    status: "Completed",
    youtubeTrailerId: "hyapq_q_kvY",
    telegramLink: "https://t.me/animeversebd/1828",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 102,
    title: "One Punch Man – Season 1 (2015)",
    year: 2015,
    type: "TV Show",
    image: "/102id.jpg",
    genre: ["Animation", "Comedy", "Superhero"],
    imdb: 8.7,
    description: "সাইতামা নামের এক সাধারণ মানুষ, যে মাত্র এক ঘুষিতে হারিয়ে দেয় যেকোনো শত্রুকে! 💪😂তবে শক্তির পাশাপাশি তার একঘেয়ে জীবনের হাস্যরসই এই সিরিজের মূল আকর্ষণ। ",
    status: "Completed",
    youtubeTrailerId: "iYPDxVoLNS8",
    telegramLink: "https://t.me/animeversebd/1882",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 103,
    title: "One Punch Man – Season 2",
    year: 2019,
    type: "TV Show",
    image: "/103id.jpg",
    genre: ["Animation", "Comedy", "Superhero"],
    imdb: 8.1,
    description: "সাইতামার এক ঘুষিতেই শেষ—কিন্তু এইবার লড়াই আরও কঠিন, আর শত্রুরা আরও বিপজ্জনক। ",
    status: "Completed",
    youtubeTrailerId: "mS1FcNK7VnI",
    telegramLink: "https://t.me/animeversebd/1910",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 104,
    title: "Naruto Shippuden – Season 6 [episode 1-31]",
    year: 2009,
    type: "TV Show",
    image: "/104id.jpg",
    genre: ["Animation", "Comedy", "Fantasy"],
    imdb: 8.7,
    description: "নারুটো আর জিরাইয়ার যাত্রা—নিজের শক্তি, ভালোবাসা আর আত্মত্যাগের মহাকাব্য। ",
    status: "Completed",
    youtubeTrailerId: "6kNR6fnoHrU",
    telegramLink: "https://t.me/animeversebd/1921",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 105,
    title: "Dr. Stone – Season 4: Science Future Arc (ドクターストーン)",
    year: 2025,
    type: "TV Show",
    image: "/105id.jpg",
    genre: ["Animation", "Comedy", "Sci-Fi"],
    imdb: 8.2,
    description: "সেনকু এবং তার টিম এবার বিজ্ঞানের শক্তিতে পৌঁছে যাচ্ছে সভ্যতার ভবিষ্যতের দোরগোড়ায়।",
    status: "Completed",
    youtubeTrailerId: "hvX-cYLRAfY",
    telegramLink: "https://t.me/animeversebd/1987",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 106,
    title: "Rent a Girlfriend – Season 1 (彼女、お借りします)",
    year: 2020,
    type: "TV Show",
    image: "/106id.jpg",
    genre: ["Animation", "Comedy", "Slice of Life"],
    imdb: 7.1,
    description: "rent a girlfriend story",
    status: "Completed",
    youtubeTrailerId: "8r3h_CI1C3s",
    telegramLink: "https://t.me/animeversebd/2038",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 107,
    title: "Solo Leveling: Season 1 (2024)",
    year: 2024,
    type: "TV Show",
    image: "/107id.jpg",
    genre: ["Animation", "Comedy", "Supernatural"],
    imdb: 8.6,
    description: "দুর্বল হান্টার জিনউ সাং একদিন সিস্টেম নামক রহস্যময় ক্ষমতা পায়, যা তাকে ধীরে ধীরে বিশ্বের সবচেয়ে শক্তিশালী হান্টারে পরিণত করে।",
    status: "Completed",
    youtubeTrailerId: "-tJMyIXjn9I",
    telegramLink: "https://t.me/animeversebd/2065",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 108,
    title: "Solo Leveling: Season 2 – Arise from the Shadow (2025)",
    year: 2025,
    type: "TV Show",
    image: "/108id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 9.0,
    description: "প্রথম সিজনের পর জিনউ সাং এখন এক অপ্রতিরোধ্য ছায়া সেনাবাহিনীর অধিপতি। তার সামনে নতুন চ্যালেঞ্জ—দেবতাদের সঙ্গে যুদ্ধের সূচনা।",
    status: "Completed",
    youtubeTrailerId: "Mgk5_MXodvY",
    telegramLink: "https://t.me/animeversebd/2072",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 109,
    title: "Naruto Shippuden – Season 7 (2009) [Episode1-08]",
    year: 2009,
    type: "TV Show",
    image: "/109id.jpg",
    genre: ["Animation", "Comedy", "Fantasy"],
    imdb: 8.7,
    description: "নারুতো ও তার সঙ্গীরা নতুন মিশনে নামে এক রহস্যময় দ্বীপে, যেখানে প্রতিটি পদক্ষেপে অপেক্ষা করছে নতুন বিপদ আর নিজের ভেতরের অন্ধকারের মুখোমুখি হওয়ার লড়াই।",
    status: "Completed",
    youtubeTrailerId: "6kNR6fnoHrU",
    telegramLink: "https://t.me/animeversebd/2080",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 110,
    title: "Naruto Shippuden – Season 8 (2009-2010)[Episode1-24]",
    year: 2010,
    type: "TV Show",
    image: "/110id.jpg",
    genre: ["Animation", "Comedy", "Fantasy"],
    imdb: 7.4,
    description: "এই সিজনে নারুতো মুখোমুখি হয় ভয়ঙ্কর পেইনের, যার আক্রমণে কনোহা গ্রাম ধ্বংসের মুখে পড়ে। কিন্তু অদম্য সাহস আর বন্ধুত্বের শক্তিতে নারুতো প্রমাণ করে — সত্যিকারের নিনজা কখনও হার মানে না। ",
    status: "Completed",
    youtubeTrailerId: "zD8GPACmks8",
    telegramLink: "https://t.me/animeversebd/2101",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 111,
    title: "classroom of the elite (Season 1)",
    year: 2017,
    type: "TV Show",
    image: "/111id.jpg",
    genre: ["Animation", "drama", "sci-fi"],
    imdb: 7.9,
    description: "গল্পের সারসংক্ষেপ: একটি বিশেষ উচ্চবিদ্যালয়ে ছাত্রদের মধ্যে প্রতিযোগিতা ও আত্মবিশ্বাসের চূড়ান্ত পরীক্ষা—যেখানে কৌশল এবং বন্ধুত্বের মাধ্যমে তারা নিজেদের পরিচয় তৈরি করে।",
    status: "Completed",
    youtubeTrailerId: "bXoll51Iig0",
    telegramLink: "https://t.me/animeversebd/2199",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 112,
    title: "classroom of the elite (Season 2)",
    year: 2022,
    type: "TV Show",
    image: "/112id.jpg",
    genre: ["Animation", "sci-fi", "drama"],
    imdb: 8.0,
    description: "দ্বিতীয় সিজনে, নতুন চ্যালেঞ্জ এবং প্রতিযোগিতার মুখোমুখি হয় ছাত্ররা, যেখানে তাদের বুদ্ধিমত্তা এবং বিচক্ষণতা আবারও পরীক্ষিত হয়।",
    status: "Completed",
    youtubeTrailerId: "hDzuuQJG6Ss",
    telegramLink: "https://t.me/animeversebd/2226",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 113,
    title: "Haikyuu!! – Season 1 (2014)",
    year: 2014,
    type: "TV Show",
    image: "/113id.jpg",
    genre: ["Animation", "Sports", "Comedy"],
    imdb: 8.7,
    description: "এই সিজনে দেখা যায় শোয়ো হিনাতাকে, এক ছোটখাটো কিন্তু স্বপ্নবাজ খেলোয়াড়, যে ভলিবলে কিংবদন্তি হতে চায়। প্রতিদ্বন্দ্বী কাগেয়ামার সঙ্গে অপ্রত্যাশিত জুটি গড়ে তারা কারাসুনো হাই স্কুলে নতুন করে দল গড়ে তোলে — যেখানে বন্ধুত্ব, পরিশ্রম আর আত্মবিশ্বাসই হয়ে ওঠে জয়ের আসল চাবিকাঠি।",
    status: "Completed",
    youtubeTrailerId: "Bp7e_Vi0WVs",
    telegramLink: "https://t.me/animeversebd/2255",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 114,
    title: "My Mother: The Animation",
    year: 2025,
    type: "TV Show",
    image: "/114id.jpg",
    genre: ["Animation", "Adventure", "Adult"],
    imdb: 8.4,
    description: "এই শিরোনামটি প্রাপ্তবয়স্ক ও যৌন বিষয়বস্তুপূর্ণ (adult explicit content) হওয়ায় আমি এর কোনো শিরোনাম বা বিবরণ তৈরি করতে পারব না।",
    status: "Completed",
    youtubeTrailerId: "nE08t1HQwkU",
    telegramLink: "https://t.me/animeversebd/2306",
    language: "english",
    views: 1700,
  },
  {
    id: 115,
    title: "Naruto Shippuden: Season 9 (2010)",
    year: 2010,
    type: "TV Show",
    image: "/115id.jpg",
    genre: ["Action", "Adventure", "Anime"],
    imdb: 8.7,
    description: "নিনজা দুনিয়ার নতুন চ্যালেঞ্জ, নতুন বন্ধুত্ব আর আত্মত্যাগের গল্প — নারুতো নিজের স্বপ্নের আরও কাছে পৌঁছে যায়। ",
    status: "Completed",
    youtubeTrailerId: "3NtW5gyNeaI",
    telegramLink: "https://t.me/animeversebd/2308",
    language: "hindi",
    views: 1700,
  },
  {
    id: 116,
    title: "Bastard!! -Heavy Metal, Dark Fantasy- (Season 1)",
    year: 2024,
    type: "TV Show",
    image: "/116id.jpg",
    genre: ["Action", "Fantasy", "Adventure"],
    imdb: 7.1,
    description: "এক অন্ধকার জাদুকর আর ভয়ঙ্কর রাজ্যের লড়াই — ধ্বংস আর মুক্তির সীমান্তে দাঁড়িয়ে! ",
    status: "Completed",
    youtubeTrailerId: "alXQXal8dw4",
    telegramLink: "https://t.me/animeversebd/2357",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 117,
    title: "Bastard!! -Heavy Metal, Dark Fantasy- (Season 2)",
    year: 2025,
    type: "TV Show",
    image: "/117id.jpg",
    genre: ["Dark Fantasy", "Magic", "Shounen"],
    imdb: 7.3,
    description: "আগুনে ফিরে এলো দার্ক শ্নাইডার — এইবার পৃথিবী রক্ষার নামে রক্তগন্ধ যুদ্ধ ",
    status: "Completed",
    youtubeTrailerId: "UP3FnxiT8RI",
    telegramLink: "https://t.me/animeversebd/2366",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 118,
    title: "Takopi’s Original Sin (Season 1)",
    year: 2010,
    type: "TV Show",
    image: "/118id.jpg",
    genre: ["Action", "Sci-Fi", "Drama"],
    imdb: 8.4,
    description: "এক ছোট্ট এলিয়েন আর এক শিশুর দুঃখভরা পৃথিবী — যেখানে নির্দোষতাও অপরাধ  ",
    status: "Completed",
    youtubeTrailerId: "pDNkpj2ERao",
    telegramLink: "https://t.me/animeversebd/2373",
    language: "hindi",
    views: 1700,
  },
  {
    id: 119,
    title: "Heroines Run the Show (Season 1)",
    year: 2025,
    type: "TV Show",
    image: "/119id.jpg",
    genre: ["Animation", "School", "Music"],
    imdb: 7.5,
    description: "মিউজিক আর ভালোবাসার টানাপোড়েনে এক সাধারণ মেয়ের অসাধারণ যাত্রা ",
    status: "Completed",
    youtubeTrailerId: "y20zBmpuSVY",
    telegramLink: "https://t.me/animeversebd/2377",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 120,
    title: "Hunter x Hunter (Season 2)",
    year: 2023,
    type: "TV Show",
    image: "/120id.jpg",
    genre: ["Animation", "Fantasy", "Adventure"],
    imdb: 9.0,
    description: "গন আর কিলুয়া এবার প্রবেশ করে ইয়র্কনিউ শহরের অপরাধের জগতে ",
    status: "Completed",
    youtubeTrailerId: "aa8XPmXboOw",
    telegramLink: "https://t.me/animeversebd/2404",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 121,
    title: "Food Wars!: Shokugeki no Soma (Season 1)",
    year: 2025,
    type: "TV Show",
    image: "/121id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 8.2,
    description: "রান্নার ময়দানে যুদ্ধ! সোমা ইউকিহিরার স্বপ্ন – বিশ্বের সেরা শেফ হওয়া ",
    status: "Completed",
    youtubeTrailerId: "z4vihPwUBls",
    telegramLink: "https://t.me/animeversebd/2408",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 122,
    title: "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs (Season 1)",
    year: 2025,
    type: "TV Show",
    image: "/122id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 7.6,
    description: "এক গেমার হঠাৎ ঢুকে পড়ে নিজের খেলা দুনিয়ায় — এখন টিকে থাকাটাই তার মিশন ",
    status: "Completed",
    youtubeTrailerId: "zOdeGIrQlQ8",
    telegramLink: "https://t.me/animeversebd/2415",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 123,
    title: "Shinchan Spin-Off (Season 3)",
    year: 2024,
    type: "TV Show",
    image: "/123id.jpg",
    genre: ["Animation", "Comedy", "Fantasy"],
    imdb: 7.0,
    description: "শিনচানের পাগলামি এবার আরও রঙিন – ছোট্ট ছেলেটির বড় বড় দুষ্টুমি ",
    status: "Completed",
    youtubeTrailerId: "g1Y1v96KGXA",
    telegramLink: "https://t.me/animeversebd/2420",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 124,
    title: "Shinchan Spin-Off (Season 4)",
    year: 2025,
    type: "TV Show",
    image: "/124id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 7.2,
    description: "পরিবার, বন্ধুত্ব আর হাসির বন্যা – শিনচান ফিরেছে নতুন অ্যাডভেঞ্চার নিয়ে ",
    status: "Completed",
    youtubeTrailerId: "fcVy846GFXA",
    telegramLink: "https://t.me/animeversebd/2422",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 125,
    title: "Vinland Saga (Season 1)",
    year: 2024,
    type: "TV Show",
    image: "/125id.jpg",
    genre: ["Animation", "Adventure", "Family"],
    imdb: 8.8,
    description: "ভাইকিংদের নিষ্ঠুর পৃথিবীতে থরফিনের প্রতিশোধ আর স্বাধীনতার কাহিনি ",
    status: "Completed",
    youtubeTrailerId: "FlPs7EdBmNA",
    telegramLink: "https://t.me/animeversebd/2424",
    language: "hindi",
    views: 1700,
  },
  {
    id: 126,
    title: "Vinland Saga (Season 2)",
    year: 2025,
    type: "TV Show",
    image: "/126id.jpg",
    genre: ["Animation", "Adventure", "Historical"],
    imdb: 9.0,
    description: "প্রতিশোধ শেষে আসে আত্মঅনুসন্ধান — এক যোদ্ধার আত্মার শান্তির পথ ",
    status: "Completed",
    youtubeTrailerId: "cfme7JslzoQ",
    telegramLink: "https://t.me/animeversebd/2435",
    language: "hindi",
    views: 1700,
  },
  {
    id: 127,
    title: "Haikyuu!! (Season 2)",
    year: 2016,
    type: "TV Show",
    image: "/127id.jpg",
    genre: ["Animation", "Sports", "Shounen"],
    imdb: 8.9,
    description: "নতুন টুর্নামেন্ট, নতুন প্রতিদ্বন্দ্বী — কারাসুনোর দল উড়ছে আরও উঁচুতে! ",
    status: "Completed",
    youtubeTrailerId: "3AJNuyXbCO4",
    telegramLink: "https://t.me/animeversebd/2442",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 128,
    title: "Haikyuu!! (Season 3)",
    year: 2018,
    type: "TV Show",
    image: "/128id.jpg",
    genre: ["Animation", "Sports", "Teamwork"],
    imdb: 9.1,
    description: "এক ম্যাচ, এক লক্ষ্য — শিরাটোরিজাওয়ার বিরুদ্ধে লড়াই, যেখানে প্রতিটি পয়েন্টই জীবন-মরণ! ",
    status: "Completed",
    youtubeTrailerId: "3AJNuyXbCO4",
    telegramLink: "https://t.me/animeversebd/2495",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 129,
    title: "Hunter x Hunter (Season 3 – 2012)",
    year: 2012,
    type: "TV Show",
    image: "/129id.jpg",
    genre: ["Action", "Fantasy", "Adventure"],
    imdb: 9.0,
    description: "গন ও কিলুয়া নতুন চ্যালেঞ্জে নামছে — গ্রিড আইল্যান্ডের রহস্যে লুকিয়ে আছে শক্তি, বন্ধুত্ব আর সাহসের গল্প ",
    status: "Completed",
    youtubeTrailerId: "aa8XPmXboOw",
    telegramLink: "https://t.me/animeversebd/2522",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 130,
    title: "Hunter x Hunter (Season 4 – 2013)",
    year: 2013,
    type: "TV Show",
    image: "/130id.jpg",
    genre: ["Dark Fantasy", "Magic", "Shounen"],
    imdb: 9.2,
    description: "কিমেরা অ্যান্ট আর্ক — মানবতা, ত্যাগ আর নায়কোচিত যুদ্ধের এক আবেগময় অধ্যায় ",
    status: "Completed",
    youtubeTrailerId: "aa8XPmXboOw",
    telegramLink: "https://t.me/animeversebd/2527",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 131,
    title: "Naruto Shippuden (Season 10 – 2011)[EP-1-25]",
    year: 2011,
    type: "TV Show",
    image: "/131id.jpg",
    genre: ["Action", "Sci-Fi", "Drama"],
    imdb: 8.7,
    description: "যুদ্ধের প্রান্তে দাঁড়িয়ে নারুতো শিখছে আসল নিনজা হওয়ার অর্থ — আত্মত্যাগ, বিশ্বাস আর বন্ধুত্বের শক্তি ",
    status: "Completed",
    youtubeTrailerId: "6kNR6fnoHrU",
    telegramLink: "https://t.me/animeversebd/2532",
    language: "hindi",
    views: 1700,
  },
]
