export interface AnimeDetail {
  id: number
  title: string
  year: number
  type: string
  image: string
  genre: string[]
  imdb: number
  description: string
  episodes?: number
  status: string
  youtubeTrailerId: string
  telegramLink: string
  language: string
  views?: number
}

export const animeDatabase: AnimeDetail[] = [
  {
    id: 1,
    title: "Spirited Away",
    year: 2001,
    type: "Movie",
    image: "/1id.jpg",
    genre: ["Action", "Drama", "Thriller"],
    imdb: 9.1,
    description: "A magical journey to a spirit world beyond imagination.",
    status: "Completed",
    youtubeTrailerId: "aL-97TEa43Y",
    telegramLink: "https://t.me/animeversebd/9",
    language: "Hindi",
    views: 1250,
  },
  {
    id: 2,
    title: "The Monkey King",
    year: 2023,
    type: "Movie",
    image: "/2id.jpg",
    genre: ["Action", "Supernatural", "Historical"],
    imdb: 5.6,
    description: "এক কিংবদন্তীর শুরু, এক অসাধারণ অভিযান।",
    status: "Completed",
    youtubeTrailerId: "0pmIANSKkdo",
    telegramLink: "https://t.me/animeverse_bd",
    language: "Hindi",
    views: 2340,
  },
  {
    id: 3,
    title: "Your Name",
    year: 2016,
    type: "Movie",
    image: "/3id.jpg",
    genre: ["Action", "School", "Supernatural"],
    imdb: 8.4,
    description: "দুই হৃদয়ের অলৌকিক গল্প, যা সময় ও দূরত্বকে ছাপিয়ে যায়।",
    status: "Completed",
    youtubeTrailerId: "_oWzYOwXn-o",
    telegramLink: "https://t.me/animeversebd/13",
    language: "Hindi",
    views: 3450,
  },
  {
    id: 4,
    title: "A Whisker Away",
    year: 2020,
    type: "Movie",
    image: "/4id.jpg",
    genre: ["Adventure", "Comedy", "Action"],
    imdb: 6.7,
    description: "A magical adventure with unexpected twists.",
    status: "Completed",
    youtubeTrailerId: "zGGp2RVoPdU",
    telegramLink: "https://t.me/animeversebd/17",
    language: "Hindi",
    views: 1890,
  },
  {
    id: 5,
    title: "Drifting Home",
    year: 2022,
    type: "Movie",
    image: "/5id.jpg",
    genre: ["Action", "Martial Arts", "Adventure"],
    imdb: 6.5,
    description: "A heartwarming story of friendship and adventure.",
    status: "Completed",
    youtubeTrailerId: "zY5O9JRPKLY",
    telegramLink: "https://t.me/animeversebd/19",
    language: "Hindi",
    views: 1567,
  },
  {
    id: 6,
    title: "Once Upon a Witch's Death Season 1",
    year: 2025,
    type: "TV Show",
    image: "/6id.jpg",
    genre: ["Action", "Adventure", "Martial Arts"],
    imdb: 8.7,
    description: "A thrilling tale of magic and mystery.",
    status: "Ongoing",
    youtubeTrailerId: "FerOCv5eOHI",
    telegramLink: "https://t.me/animeversebd/21",
    language: "Hindi",
    views: 2100,
  },
  {
    id: 7,
    title: "A Great Cleric Season 1",
    year: 2023,
    type: "TV Show",
    image: "/7id.jpg",
    genre: ["Superhero", "School", "Action"],
    imdb: 7.5,
    description: "An epic journey of a powerful cleric.",
    status: "Completed",
    youtubeTrailerId: "susqUMviH_E",
    telegramLink: "https://t.me/animeversebd/46",
    language: "Hindi",
    views: 1750,
  },
  {
    id: 8,
    title: "Rurouni Kenshin Season 1",
    year: 2023,
    type: "TV Show",
    image: "/8id.jpg",
    genre: ["Thriller", "Supernatural", "Psychological"],
    imdb: 7.9,
    description: "A legendary swordsman's journey through time.",
    status: "Completed",
    youtubeTrailerId: "ZONOltoCdP4",
    telegramLink: "https://t.me/animeversebd/73",
    language: "Hindi",
    views: 1900,
  },
  {
    id: 9,
    title: "A Couple of Cuckoos Season 1",
    year: 2022,
    type: "TV Show",
    image: "/9id.jpg",
    genre: ["Comedy", "Action", "Supernatural"],
    imdb: 7.1,
    description: "A hilarious romantic comedy with supernatural elements.",
    status: "Completed",
    youtubeTrailerId: "WtBwfWvUEqY",
    telegramLink: "https://t.me/animeversebd/82",
    language: "Hindi",
    views: 1600,
  },
  {
    id: 10,
    title: "The Misfit of Demon King Academy Season 1",
    year: 2020,
    type: "TV Show",
    image: "/10id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 7.3,
    description: "A powerful demon king returns to his academy.",
    status: "Completed",
    youtubeTrailerId: "e8YBesRKq_U",
    telegramLink: "https://t.me/animeversebd/137",
    language: "Hindi",
    views: 1800,
  },
  {
    id: 11,
    title: "Shangri La Frontier Season 2",
    year: 2025,
    type: "TV Show",
    image: "/11id.jpg",
    genre: ["Action", "Adventure", "Fantasy", "Game"],
    imdb: 8.6,
    description: "An epic gaming adventure continues.",
    status: "Ongoing",
    youtubeTrailerId: "R_7Okd4X1lU",
    telegramLink: "https://t.me/animeversebd/193",
    language: "Hindi",
    views: 2200,
  },
  {
    id: 12,
    title: "Attack on Titan Season 1",
    year: 2013,
    type: "TV Show",
    image: "/12id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 9.0,
    description: "Humanity fights for survival against giant titans.",
    status: "Completed",
    youtubeTrailerId: "LajOXSdyBeE",
    telegramLink: "https://t.me/animeversebd/198",
    language: "Hindi",
    views: 2500,
  },
  {
    id: 13,
    title: "Attack on Titan Season 2",
    year: 2017,
    type: "TV Show",
    image: "/13id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 8.9,
    description: "The battle against titans intensifies.",
    status: "Completed",
    youtubeTrailerId: "X2WGyFRKb8Y",
    telegramLink: "https://t.me/animeversebd/250",
    language: "Hindi",
    views: 2400,
  },
  {
    id: 14,
    title: "Attack on Titan Season 3",
    year: 2018,
    type: "TV Show",
    image: "/14id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 9.2,
    description: "Secrets of the titans are revealed.",
    status: "Completed",
    youtubeTrailerId: "mBGyz4G60cQ",
    telegramLink: "https://t.me/animeversebd/273",
    language: "Hindi",
    views: 2600,
  },
  {
    id: 15,
    title: "Attack on Titan Season 4",
    year: 2020,
    type: "TV Show",
    image: "/15id.jpg",
    genre: ["Action", "Supernatural", "Adventure"],
    imdb: 9.3,
    description: "The final season brings epic conclusions.",
    status: "Completed",
    youtubeTrailerId: "cR0zTG2czV0",
    telegramLink: "https://t.me/animeversebd/318",
    language: "Hindi",
    views: 2700,
  },
  {
    id: 16,
    title: "Olaf Presents Season 1",
    year: 2021,
    type: "TV Show",
    image: "/16id.jpg",
    genre: ["Animation", "Comedy", "Short"],
    imdb: 7.3,
    description: "Olaf presents hilarious Disney stories.",
    status: "Completed",
    youtubeTrailerId: "2Stzk2aopxs",
    telegramLink: "https://t.me/animeversebd/376",
    language: "English",
    views: 1700,
  },
  {
    id: 17,
    title: "Brave",
    year: 2012,
    type: "Movie",
    image: "/17id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 7.1,
    description: "A brave princess fights for her destiny.",
    status: "Completed",
    youtubeTrailerId: "fyP0IGEzr4s",
    telegramLink: "https://t.me/animeversebd/389",
    language: "English",
    views: 1650,
  },
  {
    id: 18,
    title: "DC League of Super-Pets",
    year: 2022,
    type: "Movie",
    image: "/18id.jpg",
    genre: ["Animation", "Action", "Comedy"],
    imdb: 7.2,
    description: "Superhero pets save the day.",
    status: "Completed",
    youtubeTrailerId: "dgtFO6ANznY",
    telegramLink: "https://t.me/animeversebd/391",
    language: "English/Hindi",
    views: 1750,
  },
  {
    id: 19,
    title: "Doraemon: Nobita's Chronicle of the Moon Exploration",
    year: 2019,
    type: "Movie",
    image: "/19id.jpg",
    genre: ["Animation", "Sci-Fi", "Adventure"],
    imdb: 6.7,
    description: "Doraemon and Nobita explore the moon.",
    status: "Completed",
    youtubeTrailerId: "w7Iz-zsltjw",
    telegramLink: "https://t.me/animeversebd/393",
    language: "Hindi",
    views: 1550,
  },
  {
    id: 20,
    title: "Justice Society: World War II",
    year: 2021,
    type: "Movie",
    image: "/20id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 6.4,
    description: "Superheroes fight in World War II.",
    status: "Completed",
    youtubeTrailerId: "qx2zoSk42BI",
    telegramLink: "https://t.me/animeversebd/395",
    language: "Hindi",
    views: 1450,
  },
  {
    id: 21,
    title: "Puss in Boots: The Last Wish",
    year: 2022,
    type: "Movie",
    image: "/21id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 7.8,
    description: "Puss in Boots goes on one last adventure.",
    status: "Completed",
    youtubeTrailerId: "tsTLlZ32SpI",
    telegramLink: "https://t.me/animeversebd/397",
    language: "Hindi",
    views: 1850,
  },
  {
    id: 22,
    title: "Constantine: City of Demons",
    year: 2018,
    type: "Movie",
    image: "/22id.jpg",
    genre: ["Animation", "Action", "Fantasy"],
    imdb: 7.4,
    description: "Constantine battles demons in the city.",
    status: "Completed",
    youtubeTrailerId: "6vL--ZrHC6U",
    telegramLink: "https://t.me/animeversebd/399",
    language: "English/Hindi",
    views: 1750,
  },
  {
    id: 23,
    title: "Doraemon: Nobita and the Kingdom of Clouds",
    year: 1992,
    type: "Movie",
    image: "/23id.jpg",
    genre: ["Animation", "Adventure", "Family"],
    imdb: 7.0,
    description: "Doraemon and friends discover a cloud kingdom.",
    status: "Completed",
    youtubeTrailerId: "6ndjhJo2zFw",
    telegramLink: "https://t.me/animeversebd/401",
    language: "Hindi",
    views: 1600,
  },
  {
    id: 24,
    title: "Hotel Transylvania 2",
    year: 2015,
    type: "Movie",
    image: "/24id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 6.6,
    description: "Dracula's family returns for more fun.",
    status: "Completed",
    youtubeTrailerId: "E3mL9H3C2OY",
    telegramLink: "https://t.me/animeversebd/403",
    language: "English/Hindi",
    views: 1500,
  },
  {
    id: 25,
    title: "Hotel Transylvania 3: Summer Vacation",
    year: 2018,
    type: "Movie",
    image: "/25id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 6.3,
    description: "Dracula goes on a summer vacation.",
    status: "Completed",
    youtubeTrailerId: "Qvt0KnhtPBk",
    telegramLink: "https://t.me/animeversebd/405",
    language: "Hindi",
    views: 1400,
  },
  {
    id: 26,
    title: "Ainbo: Spirit of the Amazon",
    year: 2021,
    type: "Movie",
    image: "/26id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 4.8,
    description: "A girl protects the Amazon rainforest.",
    status: "Completed",
    youtubeTrailerId: "PWRtf3pc14c",
    telegramLink: "https://t.me/animeversebd/407",
    language: "Hindi",
    views: 1200,
  },
  {
    id: 27,
    title: "Onward",
    year: 2020,
    type: "Movie",
    image: "/27id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 7.4,
    description: "Two brothers go on a magical quest.",
    status: "Completed",
    youtubeTrailerId: "dLXt8r1cQVk",
    telegramLink: "https://t.me/animeversebd/409",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 28,
    title: "Zootopia",
    year: 2016,
    type: "Movie",
    image: "/28id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 8.0,
    description: "A rabbit cop and fox con artist solve crimes.",
    status: "Completed",
    youtubeTrailerId: "X4XvU9FT0NM",
    telegramLink: "https://t.me/animeversebd/411",
    language: "Hindi",
    views: 1900,
  },
  {
    id: 29,
    title: "Ben 10: Destroy All Aliens",
    year: 2012,
    type: "Movie",
    image: "/29id.jpg",
    genre: ["Animation", "Action", "Sci-Fi"],
    imdb: 7.3,
    description: "Ben 10 fights to save the world.",
    status: "Completed",
    youtubeTrailerId: "zIYZQpknKZQ",
    telegramLink: "https://t.me/animeversebd/414",
    language: "Dual Audio",
    views: 1700,
  },
  {
    id: 30,
    title: "Shrek",
    year: 2001,
    type: "Movie",
    image: "/30id.jpg",
    genre: ["Animation", "Comedy", "Fantasy"],
    imdb: 7.1,
    description: "An ogre rescues a princess.",
    status: "Completed",
    youtubeTrailerId: "V2WydtFqZP8",
    telegramLink: "https://t.me/animeversebd/416",
    language: "English/Hindi",
    views: 1650,
  },
  {
    id: 31,
    title: "Shrek 2",
    year: 2004,
    type: "Movie",
    image: "/31id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 7.2,
    description: "Shrek meets his in-laws.",
    status: "Completed",
    youtubeTrailerId: "YxXp4EB6-fQ",
    telegramLink: "https://t.me/animeversebd/418",
    language: "English",
    views: 1700,
  },
  {
    id: 32,
    title: "The Jungle Book",
    year: 1967,
    type: "Movie",
    image: "/32id.jpg",
    genre: ["Animation", "Adventure", "Family"],
    imdb: 6.7,
    description: "A boy grows up in the jungle.",
    status: "Completed",
    youtubeTrailerId: "q6ZbvucX4Pg",
    telegramLink: "https://t.me/animeversebd/419",
    language: "Dual Audio",
    views: 1550,
  },
  {
    id: 33,
    title: "The Secret Life of Pets 2",
    year: 2019,
    type: "Movie",
    image: "/33id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 6.4,
    description: "Pets go on new adventures.",
    status: "Completed",
    youtubeTrailerId: "Id9iHnlOZaI",
    telegramLink: "https://t.me/animeversebd/421",
    language: "English",
    views: 1450,
  },
  {
    id: 34,
    title: "Turbo",
    year: 2013,
    type: "Movie",
    image: "/34id.jpg",
    genre: ["Animation", "Adventure", "Comedy"],
    imdb: 7.8,
    description: "A snail dreams of racing.",
    status: "Completed",
    youtubeTrailerId: "VlRtm8Gh9PQ",
    telegramLink: "https://t.me/animeversebd/423",
    language: "Dual Audio",
    views: 2890,
  },
  {
    id: 35,
    title: "White Snake",
    year: 2019,
    type: "Movie",
    image: "/35id.jpg",
    genre: ["Animation", "Fantasy", "Romance"],
    imdb: 7.4,
    description: "A magical love story unfolds.",
    status: "Completed",
    youtubeTrailerId: "RYKRko-yaO4",
    telegramLink: "https://t.me/animeversebd/425",
    language: "Dual Audio",
    views: 1750,
  },
  {
    id: 36,
    title: "Wonder Park",
    year: 2019,
    type: "Movie",
    image: "/36id.jpg",
    genre: ["Animation", "Family", "Fantasy"],
    imdb: 7.0,
    description: "A girl brings her imagination to life.",
    status: "Completed",
    youtubeTrailerId: "kNIyjsmoKts",
    telegramLink: "https://t.me/animeversebd/427",
    language: "English/Hindi",
    views: 1678,
  },
  {
    id: 37,
    title: "Mojib Bai",
    year: 2015,
    type: "Movie",
    image: "/37id.jpg",
    genre: ["Animation", "Adventure", "Action"],
    imdb: 6.6,
    description: "A Bangladeshi animated adventure.",
    status: "Completed",
    youtubeTrailerId: "givLtqsybMo",
    telegramLink: "https://t.me/animeversebd/429",
    language: "Bangla",
    views: 1500,
  },
  {
    id: 38,
    title: "Madan Senki Ryukendo",
    year: 2006,
    type: "TV Show",
    image: "/38id.jpg",
    genre: ["Action", "Fantasy", "Tokusatsu"],
    imdb: 7.3,
    description: "A warrior fights for justice.",
    status: "Completed",
    youtubeTrailerId: "vNgF_ZbVZHk",
    telegramLink: "https://t.me/animeversebd/431",
    language: "Japanese/English",
    views: 1700,
  },
  {
    id: 39,
    title: "What If... Season 1",
    year: 2021,
    type: "TV Show",
    image: "/39id.jpg",
    genre: ["Animation", "Action", "Sci-Fi"],
    imdb: 7.1,
    description: "Explore alternate Marvel universes.",
    status: "Completed",
    youtubeTrailerId: "I7ztyv9dwgo",
    telegramLink: "https://t.me/animeversebd/536",
    language: "English/Hindi",
    views: 1650,
  },
  {
    id: 40,
    title: "SK8 the Infinity Season 1",
    year: 2021,
    type: "TV Show",
    image: "/40id.jpg",
    genre: ["Sports", "Action", "Comedy"],
    imdb: 7.2,
    description: "Underground skateboarding battles.",
    status: "Completed",
    youtubeTrailerId: "cBPPj83KjTQ",
    telegramLink: "https://t.me/animeversebd/555",
    language: "Japanese/Hindi",
    views: 1700,
  },
  {
    id: 41,
    title: "Death Note Season 1",
    year: 2006,
    type: "TV Show",
    image: "/41id.jpg",
    genre: ["Mystery", "Supernatural", "Thriller"],
    imdb: 8.9,
    description: "A notebook that can kill anyone.",
    status: "Completed",
    youtubeTrailerId: "R5JgNbmQBcY",
    telegramLink: "https://t.me/animeversebd/578",
    language: "Japanese/Hindi",
    views: 2400,
  },
  {
    id: 42,
    title: "Roll No. 21 Season 1",
    year: 2010,
    type: "TV Show",
    image: "/42id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 8.1,
    description: "A student's hilarious adventures.",
    status: "Completed",
    youtubeTrailerId: "Zx4Yu2cujqI",
    telegramLink: "https://t.me/animeversebd/585",
    language: "Hindi",
    views: 2000,
  },
  {
    id: 43,
    title: "Roll No. 21 Season 2",
    year: 2013,
    type: "TV Show",
    image: "/43id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 7.8,
    description: "More adventures of Roll No. 21.",
    status: "Completed",
    youtubeTrailerId: "LTeXi8LgTy4",
    telegramLink: "https://t.me/animeversebd/632",
    language: "Dual Audio",
    views: 1900,
  },
  {
    id: 44,
    title: "Baki Hanma Season 2",
    year: 2023,
    type: "TV Show",
    image: "/44id.jpg",
    genre: ["Action", "Martial Arts", "Anime"],
    imdb: 7.4,
    description: "Intense martial arts battles.",
    status: "Completed",
    youtubeTrailerId: "KN98VzNwjOY",
    telegramLink: "https://t.me/animeversebd/685",
    language: "Japanese/Hindi",
    views: 1750,
  },
  {
    id: 45,
    title: "Blue Eye Samurai Season 1",
    year: 2023,
    type: "TV Show",
    image: "/45id.jpg",
    genre: ["Animation", "Action", "Drama"],
    imdb: 7.0,
    description: "A samurai's quest for revenge.",
    status: "Completed",
    youtubeTrailerId: "WfzXxTq_W6k",
    telegramLink: "https://t.me/animeversebd/738",
    language: "Hindi/Japanese",
    views: 4567,
  },
  {
    id: 46,
    title: "Puss in Boots",
    year: 2011,
    type: "Movie",
    image: "/46id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 6.6,
    description: "The origin story of Puss in Boots.",
    status: "Completed",
    youtubeTrailerId: "tsTLlZ32SpI",
    telegramLink: "https://t.me/animeversebd/755",
    language: "English/Hindi",
    views: 2234,
  },
  {
    id: 47,
    title: "Invincible Season 1",
    year: 2021,
    type: "TV Show",
    image: "/47id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 6.6,
    description: "A young superhero's journey begins.",
    status: "Completed",
    youtubeTrailerId: "qR2xlrQiHDk",
    telegramLink: "https://t.me/animeversebd/757",
    language: "English/Hindi",
    views: 1500,
  },
  {
    id: 48,
    title: "Invincible Season 2",
    year: 2023,
    type: "TV Show",
    image: "/48id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 6.6,
    description: "Invincible faces greater challenges.",
    status: "Completed",
    youtubeTrailerId: "13ahG2dEiWQ",
    telegramLink: "https://t.me/animeversebd/776",
    language: "English/Hindi",
    views: 1500,
  },
  {
    id: 49,
    title: "Onimusha Season 1",
    year: 2023,
    type: "TV Show",
    image: "/49id.jpg",
    genre: ["Animation", "Action", "Samurai"],
    imdb: 6.6,
    description: "A samurai fights supernatural forces.",
    status: "Completed",
    youtubeTrailerId: "SqWxZEvMrdo",
    telegramLink: "https://t.me/animeversebd/779",
    language: "Japanese/Hindi",
    views: 1500,
  },
  {
    id: 50,
    title: "Tokyo Revengers Season 2",
    year: 2023,
    type: "TV Show",
    image: "/50id.jpg",
    genre: ["Action", "Drama", "Supernatural"],
    imdb: 8.2,
    description: "Time travel and gang warfare.",
    status: "Completed",
    youtubeTrailerId: "eNZSurcYTW8",
    telegramLink: "https://t.me/animeversebd/797",
    language: "Japanese/Hindi",
    views: 2100,
  },
  {
    id: 51,
    title: "Captain Laserhawk: A Blood Dragon Remix Season 1",
    year: 2023,
    type: "TV Show",
    image: "/51id.jpg",
    genre: ["Animation", "Action", "Sci-Fi"],
    imdb: 7.9,
    description: "A cyberpunk action adventure.",
    status: "Completed",
    youtubeTrailerId: "1cqWBOVszYo",
    telegramLink: "https://t.me/animeversebd/825",
    language: "English",
    views: 1900,
  },
  {
    id: 52,
    title: "Ultraman Season 3",
    year: 2023,
    type: "TV Show",
    image: "/52id.jpg",
    genre: ["Action", "Sci-Fi", "Superhero"],
    imdb: 9.0,
    description: "The ultimate superhero battles.",
    status: "Completed",
    youtubeTrailerId: "Tvb-9DWt45Q",
    telegramLink: "https://t.me/animeversebd/837",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 53,
    title: "Rurouni Kenshin Season 1 Ep 5-8",
    year: 2023,
    type: "TV Show",
    image: "/53id.jpg",
    genre: ["Historical", "Action", "Romance"],
    imdb: 8.0,
    description: "A legendary swordsman's tale.",
    status: "Completed",
    youtubeTrailerId: "ZONOltoCdP4",
    telegramLink: "https://t.me/animeversebd/862",
    language: "Japanese/Hindi",
    views: 3789,
  },
  {
    id: 54,
    title: "Rurouni Kenshin Season 1 Ep 13-19",
    year: 2023,
    type: "TV Show",
    image: "/54id.jpg",
    genre: ["Historical", "Action", "Romance"],
    imdb: 9.0,
    description: "Kenshin's journey continues.",
    status: "Completed",
    youtubeTrailerId: "ZONOltoCdP4",
    telegramLink: "https://t.me/animeversebd/871",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 55,
    title: "Justice League Season 1",
    year: 2001,
    type: "TV Show",
    image: "/55id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 9.2,
    description: "Earth's mightiest heroes unite.",
    status: "Completed",
    youtubeTrailerId: "9Wly6N7dSkM",
    telegramLink: "https://t.me/animeversebd/886",
    language: "English/Hindi",
    views: 5678,
  },
  {
    id: 56,
    title: "Baki Hanma Season 1",
    year: 2023,
    type: "TV Show",
    image: "/56id.jpg",
    genre: ["Action", "Martial Arts", "Anime"],
    imdb: 8.5,
    description: "The strongest fighter emerges.",
    status: "Completed",
    youtubeTrailerId: "pRYZRvYGMtc",
    telegramLink: "https://t.me/animeversebd/939",
    language: "Japanese/Hindi",
    views: 2200,
  },
  {
    id: 57,
    title: "Pokémon Ultimate Journeys Season 1",
    year: 2022,
    type: "TV Show",
    image: "/57id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 7.3,
    description: "Ash's ultimate Pokémon journey.",
    status: "Completed",
    youtubeTrailerId: "wyrWFzV5U5Y",
    telegramLink: "https://t.me/animeversebd/964",
    language: "Japanese",
    views: 1700,
  },
  {
    id: 58,
    title: "Pokémon Ultimate Journeys Season 2",
    year: 2023,
    type: "TV Show",
    image: "/58id.jpg",
    genre: ["Animation", "Adventure", "Fantasy"],
    imdb: 9.0,
    description: "The journey reaches new heights.",
    status: "Completed",
    youtubeTrailerId: "sR1hzqn8k5w",
    telegramLink: "https://t.me/animeversebd/991",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 59,
    title: "Scott Pilgrim Takes Off Season 1",
    year: 2023,
    type: "TV Show",
    image: "/59id.jpg",
    genre: ["Animation", "Comedy", "Romance", "Action"],
    imdb: 8.6,
    description: "A fresh take on Scott Pilgrim.",
    status: "Completed",
    youtubeTrailerId: "WAqJZdsV3mo",
    telegramLink: "https://t.me/animeversebd/1024",
    language: "English/Hindi",
    views: 2200,
  },
  {
    id: 60,
    title: "Ultraman Season 2",
    year: 2023,
    type: "TV Show",
    image: "/60id.jpg",
    genre: ["Action", "Sci-Fi", "Superhero"],
    imdb: 9.0,
    description: "Ultraman returns stronger.",
    status: "Completed",
    youtubeTrailerId: "AudT7Av-pv4",
    telegramLink: "https://t.me/animeversebd/1041",
    language: "Japanese/Hindi",
    views: 2500,
  },
  {
    id: 61,
    title: "Solo Leveling Season 1",
    year: 2024,
    type: "TV Show",
    image: "/61id.jpg",
    genre: ["Action", "Fantasy", "Adventure"],
    imdb: 8.4,
    description: "A hunter rises to power.",
    status: "Completed",
    youtubeTrailerId: "-tJMyIXjn9I",
    telegramLink: "https://t.me/animeversebd/1054",
    language: "Japanese/Hindi",
    views: 2100,
  },
  {
    id: 62,
    title: "Ultraman Season 1",
    year: 2019,
    type: "TV Show",
    image: "/62id.jpg",
    genre: ["Action", "Sci-Fi", "Superhero"],
    imdb: 6.8,
    description: "The beginning of Ultraman.",
    status: "Completed",
    youtubeTrailerId: "hLfNecWqzJs",
    telegramLink: "https://t.me/animeversebd/1057",
    language: "Japanese",
    views: 1800,
  },
  {
    id: 63,
    title: "Akuma Kun Season 1",
    year: 2023,
    type: "TV Show",
    image: "/63id.jpg",
    genre: ["Fantasy", "Supernatural", "Adventure"],
    imdb: 6.5,
    description: "A demon's supernatural adventures.",
    status: "Completed",
    youtubeTrailerId: "ZZQ7BaCunsw",
    telegramLink: "https://t.me/animeversebd/1084",
    language: "Japanese/Hindi",
    views: 1600,
  },
  {
    id: 64,
    title: "My Daemon Season 1",
    year: 2023,
    type: "TV Show",
    image: "/64id.jpg",
    genre: ["Fantasy", "Sci-Fi", "Drama"],
    imdb: 6.7,
    description: "A girl and her daemon companion.",
    status: "Completed",
    youtubeTrailerId: "vYTKsskxPV0",
    telegramLink: "https://t.me/animeversebd/1109",
    language: "Japanese/Hindi",
    views: 1700,
  },
  {
    id: 65,
    title: "Prison School Season 1",
    year: 2015,
    type: "TV Show",
    image: "/65id.jpg",
    genre: ["Comedy", "Ecchi", "School Life"],
    imdb: 7.6,
    description: "Boys in an all-girls prison.",
    status: "Completed",
    youtubeTrailerId: "l1v5WqCJva4",
    telegramLink: "https://t.me/animeversebd/1136",
    language: "Japanese/Hindi",
    views: 1800,
  },
  {
    id: 66,
    title: "Spy x Family Season 1",
    year: 2022,
    type: "TV Show",
    image: "/66id.jpg",
    genre: ["Action", "Comedy", "Family"],
    imdb: 8.3,
    description: "A spy, assassin, and psychic form a family.",
    status: "Completed",
    youtubeTrailerId: "fi_k0iAN8BE",
    telegramLink: "https://t.me/animeversebd/1161",
    language: "Japanese/Hindi",
    views: 2000,
  },
  {
    id: 67,
    title: "Mashle: Magic and Muscles Season 1",
    year: 2023,
    type: "TV Show",
    image: "/67id.jpg",
    genre: ["Fantasy", "Comedy", "Action"],
    imdb: 7.4,
    description: "Magic meets muscles in this adventure.",
    status: "Completed",
    youtubeTrailerId: "nDHAgFP3wxU",
    telegramLink: "https://t.me/animeversebd/1212",
    language: "Japanese/Hindi",
    views: 1900,
  },
  {
    id: 68,
    title: "My Love Story with Yamada-kun at Lv999",
    year: 2023,
    type: "TV Show",
    image: "/68id.jpg",
    genre: ["Romance", "Comedy", "Slice of Life"],
    imdb: 7.5,
    description: "A gamer love story unfolds.",
    status: "Completed",
    youtubeTrailerId: "im1jnkHA7wg",
    telegramLink: "https://t.me/animeversebd/1235",
    language: "Hindi/Japanese",
    views: 1750,
  },
  {
    id: 69,
    title: "Sgt. Stubby: An American Hero",
    year: 2018,
    type: "Movie",
    image: "/69id.jpg",
    genre: ["Adventure", "Family", "History"],
    imdb: 6.8,
    description: "A dog's heroic journey in war.",
    status: "Completed",
    youtubeTrailerId: "n3mbKogOWJ0",
    telegramLink: "https://t.me/animeversebd/1258",
    language: "English",
    views: 1600,
  },
  {
    id: 70,
    title: "Stuart Little",
    year: 1999,
    type: "Movie",
    image: "/70id.jpg",
    genre: ["Adventure", "Family", "Comedy"],
    imdb: 6.7,
    description: "A mouse's adventures in the city.",
    status: "Completed",
    youtubeTrailerId: "Wlo-sYrADlw",
    telegramLink: "https://t.me/animeversebd/1260",
    language: "Hindi",
    views: 1550,
  },
  {
    id: 71,
    title: "Stuart Little 2",
    year: 2002,
    type: "Movie",
    image: "/71id.jpg",
    genre: ["Adventure", "Family", "Comedy"],
    imdb: 6.7,
    description: "Stuart's new adventure continues.",
    status: "Completed",
    youtubeTrailerId: "k--OdtbKyqE",
    telegramLink: "https://t.me/animeversebd/1262",
    language: "Hindi",
    views: 1600,
  },
  {
    id: 72,
    title: "Stuart Little 3",
    year: 2005,
    type: "Movie",
    image: "/72id.jpg",
    genre: ["Adventure", "Family", "Comedy"],
    imdb: 6.7,
    description: "Stuart's final adventure.",
    status: "Completed",
    youtubeTrailerId: "trBgCyZpaa4",
    telegramLink: "https://t.me/animeversebd/1264",
    language: "Hindi",
    views: 1650,
  },
  {
    id: 73,
    title: "I Want to Eat Your Pancreas",
    year: 2018,
    type: "Movie",
    image: "/73id.jpg",
    genre: ["Drama", "Romance"],
    imdb: 8.1,
    description: "A touching love story.",
    status: "Completed",
    youtubeTrailerId: "uqQySB0NO4U",
    telegramLink: "https://t.me/animeversebd/1270",
    language: "Hindi",
    views: 1700,
  },
  {
    id: 74,
    title: "Suzume",
    year: 2022,
    type: "Movie",
    image: "/74id.jpg",
    genre: ["Fantasy", "Adventure", "Drama"],
    imdb: 7.6,
    description: "A girl's magical journey.",
    status: "Completed",
    youtubeTrailerId: "ciQc8lfvSm0",
    telegramLink: "https://t.me/animeversebd/1272",
    language: "Hindi",
    views: 1800,
  },
  {
    id: 75,
    title: "Adam's Sweet Agony",
    year: 2023,
    type: "TV Show",
    image: "/75id.jpg",
    genre: ["Romance", "Sci-Fi", "Adult Comedy"],
    imdb: 7.6,
    description: "A romantic sci-fi comedy.",
    status: "Completed",
    youtubeTrailerId: "DzhRc0fsVrY",
    telegramLink: "https://t.me/animeversebd/1274",
    language: "Japanese",
    views: 1750,
  },
  {
    id: 76,
    title: "Bye Bye, Earth Season 1",
    year: 2024,
    type: "TV Show",
    image: "/76id.jpg",
    genre: ["Fantasy", "Adventure", "Drama"],
    imdb: 8.2,
    description: "An epic farewell to Earth.",
    status: "Ongoing",
    youtubeTrailerId: "33rmUkfc7tM",
    telegramLink: "https://t.me/animeversebd/1289",
    language: "Hindi",
    views: 1900,
  },
  {
    id: 77,
    title: "Dr. Stone Season 1",
    year: 2019,
    type: "TV Show",
    image: "/77id.jpg",
    genre: ["Animation", "Comedy", "Adventure"],
    imdb: 8.6,
    description: "Science rebuilds civilization.",
    status: "Completed",
    youtubeTrailerId: "Zlf8N7yrPwg",
    telegramLink: "https://t.me/animeversebd/1311",
    language: "English/Hindi",
    views: 2100,
  },
  {
    id: 78,
    title: "Dr. Stone: Stone Wars Season 2",
    year: 2021,
    type: "TV Show",
    image: "/78id.jpg",
    genre: ["Animation", "Action", "Superhero"],
    imdb: 9.1,
    description: "The stone wars intensify.",
    status: "Completed",
    youtubeTrailerId: "Nf8HZT3orUE",
    telegramLink: "https://t.me/animeversebd/1360",
    language: "English/Hindi",
    views: 2300,
  },
  {
    id: 79,
    title: "My Happy Marriage Season 1",
    year: 2023,
    type: "TV Show",
    image: "/79id.jpg",
    genre: ["Romance", "Drama", "Fantasy"],
    imdb: 7.6,
    description: "A marriage of convenience becomes love.",
    status: "Completed",
    youtubeTrailerId: "XoduKRPJeTI",
    telegramLink: "https://t.me/animeversebd/1383",
    language: "Japanese/Hindi",
    views: 1850,
  },
  {
    id: 80,
    title: "Lord of the Mysteries Season 1",
    year: 2025,
    type: "TV Show",
    image: "/80id.jpg",
    genre: ["Mystery", "Fantasy", "Action", "Suspense"],
    imdb: 8.6,
    description: "Mysteries unfold in a dark world.",
    status: "Ongoing",
    youtubeTrailerId: "Pdv0Uoh-brs",
    telegramLink: "https://t.me/animeversebd/1410",
    language: "Chinese/Hindi",
    views: 2200,
  },
  {
    id: 81,
    title: "Sakamoto Days Season 1",
    year: 2025,
    type: "TV Show",
    image: "/81id.jpg",
    genre: ["Action", "Comedy", "Thriller"],
    imdb: 8.2,
    description: "A retired assassin's peaceful days.",
    status: "Ongoing",
    youtubeTrailerId: "13pu4O72Rs4",
    telegramLink: "https://t.me/animeversebd/1429",
    language: "Japanese/Hindi",
    views: 2000,
  },
  {
    id: 82,
    title: "Watchmen",
    year: 2009,
    type: "Movie",
    image: "/82id.jpg",
    genre: ["Action", "Mystery", "Drama", "Superhero"],
    imdb: 7.6,
    description: "Superheroes in a dark world.",
    status: "Completed",
    youtubeTrailerId: "oUk6l8LCdCM",
    telegramLink: "https://t.me/animeversebd/1469",
    language: "English/Hindi",
    views: 1900,
  },
  {
    id: 83,
    title: "Watchmen",
    year: 2024,
    type: "Movie",
    image: "/83id.jpg",
    genre: ["Action", "Mystery", "Drama", "Superhero"],
    imdb: 9.0,
    description: "A new take on Watchmen.",
    status: "Completed",
    youtubeTrailerId: "Gzt7e1eP2hs",
    telegramLink: "https://t.me/animeversebd/1471",
    language: "English/Hindi",
    views: 2100,
  },
  {
    id: 84,
    title: "Demon Slayer: Kimetsu no Yaiba – Infinity Castle",
    year: 2025,
    type: "Movie",
    image: "/84id.jpg",
    genre: ["Anime", "Action", "Fantasy", "Adventure"],
    imdb: 8.0,
    description: "The final battle begins.",
    status: "Ongoing",
    youtubeTrailerId: "x7uLutVRBfI",
    telegramLink: "https://t.me/animeversebd/1486",
    language: "Japanese",
    views: 2000,
  },
  {
    id: 85,
    title: "Tower of God Season 1",
    year: 2020,
    type: "TV Show",
    image: "/85id.jpg",
    genre: ["Fantasy", "Adventure", "Mystery"],
    imdb: 7.6,
    description: "Climbing the mysterious tower.",
    status: "Completed",
    youtubeTrailerId: "9GJAE8Kj5Z4",
    telegramLink: "https://t.me/animeversebd/1488",
    language: "Japanese/Hindi",
    views: 1800,
  },
  {
    id: 86,
    title: "Demon Slayer: Kimetsu no Yaiba – Infinity Castle",
    year: 2025,
    type: "Movie",
    image: "/86id.jpg",
    genre: ["Action", "Fantasy", "Adventure"],
    imdb: 9.2,
    description: "The ultimate demon slayer battle.",
    status: "Ongoing",
    youtubeTrailerId: "0pdC1l6M8rU",
    telegramLink: "https://t.me/animeversebd/1503",
    language: "Hindi",
    views: 2300,
  },
  {
    id: 87,
    title: "The God of High School",
    year: 2020,
    type: "TV Show",
    image: "/87id.jpg",
    genre: ["Action", "Fantasy", "Martial Arts"],
    imdb: 7.2,
    description: "High school martial arts tournament.",
    status: "Completed",
    youtubeTrailerId: "yKsM3eceKWk",
    telegramLink: "https://t.me/animeversebd/1505",
    language: "Japanese/Hindi",
    views: 1750,
  },
  {
    id: 88,
    title: "Naruto Shippuden Season 1",
    year: 2002,
    type: "TV Show",
    image: "/88id.jpg",
    genre: ["Animation", "Action", "Adventure", "Fantasy"],
    imdb: 8.4,
    description: "Naruto's epic ninja journey.",
    status: "Completed",
    youtubeTrailerId: "voAYyJwgQ3I",
    telegramLink: "https://t.me/animeversebd/1508",
    language: "Hindi",
    views: 2200,
  },
  {
    id: 89,
    title: "Oggy and the Cockroaches Season 1",
    year: 1998,
    type: "TV Show",
    image: "/89id.jpg",
    genre: ["Animation", "Comedy", "Family"],
    imdb: 7.4,
    description: "A cat's hilarious battles with cockroaches.",
    status: "Completed",
    youtubeTrailerId: "m67kaN-6VQk",
    telegramLink: "https://drive.google.com/uc?export=download&id=1-hy8anFjw3urWV8VMlLbLhtCyamCuzal",
    language: "Hindi",
    views: 1700,
  },
]
